"""Generate the human-readable course map from the emitted banks."""
import json
from pathlib import Path

def write_catalog():
    root=Path(__file__).resolve().parents[2]
    courses=[json.loads(p.read_text()) for p in (root/'codelingo/courses').glob('*.json')]
    courses.sort(key=lambda c:(c['id']!='python',c['title']))
    lines=['# Course curricula','',
      'Lesson length varies by topic; every section exam contains 25 questions. '
      'The nine revised tracks each contain 20 lessons. Python retains 18 lessons '
      'and Rust retains its 26 Book-led lessons. '
      f"Total: {sum(len(c['lessons']) for c in courses)} lessons and "
      f"{sum(len(l['questions']) for c in courses for l in c['lessons']):,} exercises.",
      '', 'See [NATIVE_CURRICULA.md](NATIVE_CURRICULA.md) for the review, native topic choices, '
      'history compatibility, and validation limits. This map is regenerated by '
      '`uv run python tools/curricula/build.py`.','']
    for course in courses:
        refs={s['id']:s for s in course['sources']}
        lines+=['## '+course['title'],'',course['language'],'',
                '| Section | Lesson | Questions | References |','| --- | --- | --- | --- |']
        for lesson in course['lessons']:
            sources='; '.join('['+refs[s]['title']+']('+refs[s]['url']+')' for s in lesson['sources'])
            lines.append('| '+lesson['section']+' | '+lesson['title']+' | '+str(len(lesson['questions']))+' | '+sources+' |')
        lines.append('')
    (root/'CURRICULA.md').write_text('\n'.join(lines).rstrip()+'\n')

if __name__=='__main__':write_catalog()
