from build import S,lesson as L,emit,source
from common import basics

def ruby():
 return basics('ruby')+[
 L('strings','Strings and symbols','Double quotes interpolate expressions; single quotes usually preserve them. Symbols are immutable names, distinct from strings.',
 S('puts ~"${word}".length~','${length}','0|${next}','length counts the characters of this ASCII string.','"${word}"|:${word}'),
 S('puts "${word}".~upcase~','${upper}','${word}|nil','upcase returns uppercase text.','downcase|length'),
 S('x = ${n}\nputs ~"#{x}"~','${n}','#{x}|x','Double-quoted interpolation evaluates x.','\'#{x}\'|"x"'),
 S('p ~:${word}~.class','Symbol','String|Integer','A colon-prefixed name is a Symbol.','"${word}"|${n}')),
 L('conditions','Truthiness and branches','Only nil and false are falsey in Ruby; zero and empty strings are truthy. == compares values; && short-circuits.',
 S('puts(~0~ ? "yes" : "no")','yes','no|0','Zero is truthy, so the first branch is selected.','nil|false'),
 S('puts(~nil~ || "${word}")','${word}','nil|false','|| supplies the fallback because nil is falsey.','true|${n}'),
 S('puts(${n} ~==~ ${n})','true','false|nil','== compares the two equal integer values.','!=|<'),
 S('x = ${n}\nx += 1 ~unless~ false\nputs x','${next}','${n}|${prev}','unless executes its body when the condition is false.','if|while')),
 L('loops','Iteration and ranges','times repeats a block; each yields elements. .. includes the endpoint and ... excludes it. next skips the current iteration.',
 S('x = 0\n${n}.~times~ { x += 1 }\nputs x','${n}','0|${next}','times invokes the block ${n} times.','to_s|abs'),
 S('p (1~...~${n}).to_a.length','${prev}','${n}|${next}','The three-dot range excludes its endpoint.','..|+'),
 S('x = 0\n[${n}, ${m}].~each~ { |v| x += v }\nputs x','${add}','${mul}|0','each yields both values to the block.','clear|first'),
 S('x = 0\n3.times do |i|\n  ~next~ if i == 1\n  x += 1\nend\nputs x','2','1|3','next skips only the iteration where i is one.','break|redo')),
 L('methods','Methods and arguments','Methods return their last expression unless return exits earlier. Defaults fill omitted arguments; keyword arguments are named.',
 S('def bump(x)\n  ~x + 1~\nend\nputs bump(${n})','${next}','${n}|nil','The last expression is the method result.','x|nil'),
 S('def size(x = ${n})\n x\nend\nputs ~size~','${n}','nil|0','An omitted argument uses the default.','size(0)|size(nil)'),
 S('def label(text:)\n text\nend\nputs label(~text: "${word}"~)','${word}','nil|text','text: supplies the required keyword argument.','"${word}"|value: "${word}"'),
 S('def stop\n ~return~ ${n}\n ${m}\nend\nputs stop','${n}','${m}|nil','return exits before the next expression.','puts|print')),
 L('collections','Arrays and hashes','Arrays use zero-based indexes; hashes associate keys with values. Reading a missing hash key normally returns nil. fetch can supply a fallback.',
 S('puts [${n}, ${m}][~0~]','${n}','${m}|nil','Index zero selects the first element.','1|2'),
 S('h = {name: "${word}"}\nputs h[~:name~]','${word}','nil|name','Symbol :name is the key used in this hash.','"name"|0'),
 S('h = {}\nputs h.~fetch~(:size, ${n})','${n}','nil|0','fetch returns its default for this absent key.','delete|key?'),
 S('a = [${n}]\na ~<<~ ${m}\nputs a.length','2','1|${add}','<< appends one element in place.','==|+')),
 L('io','Input, output, and conversion','gets reads a line or nil at EOF; chomp removes a trailing record separator. to_i converts a leading integer. File blocks close handles automatically.',
 S('puts "${n}".~to_i~ + ${m}','${add}','${n}${m}|${n}','to_i converts digit text to an integer before addition.','to_s|length'),
 S('p "${word}\n".~chomp~','"${word}"','nil|""','chomp removes the trailing newline without deleting other text.','clear|length'),
 S('line = nil\np line~&.~chomp','nil','false|0','Safe navigation skips the call when the receiver is nil.','.|::'),
 S('File.~open~("notes.txt", "w") { |f| f.write("${word}") }','Writes text and closes the file','Only reads the file|Leaves the file open','The block form closes the handle when the block exits.','read|delete','What does the block form do, assuming the file can be opened?')),
 L('modules','Modules and loading','Modules provide namespaces and reusable methods. include adds instance methods; require loads a feature once. :: accesses a constant in a namespace.',
 S('module Config\n SIZE = ${n}\nend\nputs Config~::~SIZE','${n}','nil|Config',':: resolves the constant within Config.','.|->'),
 S('module Tag\n def label; "${word}"; end\nend\nclass Item\n ~include~ Tag\nend\nputs Item.new.label','${word}','nil|Tag','include makes module methods available to instances.','extend|require'),
 S('~require~ "set"','Loads the feature at most once','Reloads on every call|Declares a class','require tracks features already loaded.','load|include','What loading rule applies?'),
 S('module Box\n def self.size; ${n}; end\nend\nputs ~Box.size~','${n}','nil|Box','A method defined on self here is called on the module object.','Box.new.size|size')),
 L('errors','Exceptions and cleanup','raise signals an exception, rescue handles it, and ensure runs during normal or exceptional exit. Rescue specific errors when possible.',
 S('begin\n raise ArgumentError\n~rescue~ ArgumentError\n puts "${word}"\nend','${word}','ArgumentError escapes|nil','rescue catches the matching exception.','ensure|else'),
 S('begin\n puts ${n}\n~ensure~\n puts ${m}\nend','${n}\n${m}','${m}|${n}','ensure runs after the protected body.','rescue|else_if'),
 S('~raise~ ArgumentError, "${word}"','Raises ArgumentError','Returns a string|Returns nil','raise creates exceptional control flow with a message.','return|puts','What happens?'),
 S('begin\n Integer("bad")\nrescue ~ArgumentError~\n puts ${n}\nend','${n}','0|nil','Integer rejects invalid numeric input with ArgumentError.','NameError|NoMethodError')),
 L('objects','Objects and encapsulation','initialize sets up new objects. @ names instance state; attr_reader exposes a getter. Instances keep separate state.',
 S('class Box\n attr_reader :size\n def initialize(n); @size = n; end\nend\nputs Box.~new~(${n}).size','${n}','nil|0','new allocates an instance and invokes initialize.','initialize|allocate'),
 S('class Box\n def initialize; ~@size~ = ${n}; end\n def size; @size; end\nend\nputs Box.new.size','${n}','nil|0','@size persists as instance state across method calls.','size|@@other'),
 S('class Box\n ~attr_reader~ :size\n def initialize; @size = ${n}; end\nend\nputs Box.new.size','${n}','nil|NoMethodError','attr_reader creates the size getter.','attr_writer|private'),
 S('class Box\n def value; ${n}; end\nend\na = Box.new\nputs a.~value~','${n}','nil|Box','Dot syntax dispatches an instance method.','new|initialize')),
 L('blocks','Blocks, yield, and closures','yield invokes the supplied block. A lambda is a callable object; closures retain access to captured local variables.',
 S('def run\n ~yield~ ${n}\nend\nputs run { |x| x + 1 }','${next}','${n}|nil','yield passes ${n} to the caller block and returns its result.','return|puts'),
 S('f = ~->(x) { x * 2 }~\nputs f.call(${n})','${double}','${n}|nil','A lambda can be stored and called later.','${n}|nil'),
 S('x = ${n}\nf = -> { x }\nx = ${m}\nputs f.~call~','${m}','${n}|nil','The closure reads the captured variable after reassignment.','to_s|arity'),
 S('def run(&block)\n block.~call~(${n})\nend\nputs run { |x| x + ${m} }','${add}','${mul}|nil','&block captures the block as a callable Proc.','arity|source_location')),
 L('enumeration','Enumerable and lazy iteration','map transforms values, select keeps matches, and find returns the first match. Lazy enumerators defer traversal until values are requested.',
 S('p [${n}, ${m}].~map~ { |x| x * 2 }','[${double}, ${m_double}]','[${n}, ${m}]|nil','map builds an array of the block results.','select|each'),
 S('p [1, 2, 3].~select~ { |x| x > 1 }','[2, 3]','[1, 2, 3]|2','select keeps elements whose block result is truthy.','find|map'),
 S('puts [1, 2, 3].~find~ { |x| x > 1 }','2','3|[2, 3]','find returns the first matching element.','select|map'),
 S('p (1..${n}).~lazy~.map { |x| x * 2 }.take(2).force','[2, 4]','[1, 2]|[]','lazy defers work; force evaluates the requested first two values.','to_i|first')),
 L('mutation','Aliasing, freezing, and method lookup','Assignment shares mutable objects; dup makes a shallow copy. freeze prevents mutation of that object. super delegates to the ancestor method.',
 S('a = [${n}]\nb = a\nb ~<<~ ${m}\nputs a.length','2','1|0','Both variables refer to the same mutable array.','==|+'),
 S('a = [${n}]\nb = a.~dup~\nb << ${m}\nputs a.length','1','2|0','dup creates a separate outer array.','itself|freeze'),
 S('a = [${n}].~freeze~\na << ${m}','FrozenError','Appends successfully|Returns nil','freeze rejects attempts to modify this array.','dup|itself','What happens on the second line?'),
 S('class Base\n def size; ${n}; end\nend\nclass Child < Base\n def size; ~super~ + 1; end\nend\nputs Child.new.size','${next}','${n}|1','super invokes the inherited implementation.','nil|self'))]

def lua():
 return basics('lua')+[
 L('strings','Strings and coercion','Strings concatenate with .. and are indexed through string functions. # counts bytes, which match character counts in these ASCII examples.',
 S('print(~#~"${word}")','${length}','0|${n}','# returns this string byte length.','-|not '),
 S('print("${word}" ~..~ "${word}")','${joined}','${word}|Error','.. concatenates the strings.','+|*'),
 S('print(string.~sub~("${word}", 1, 1))','${first}','${word}|nil','sub uses one-based inclusive string positions.','rep|find'),
 S('print(string.~upper~("${word}"))','${upper}','${word}|nil','upper creates uppercase text.','lower|len')),
 L('conditions','Truthiness and expressions','Only false and nil are falsey. Zero and empty strings are truthy. and/or return operands and short-circuit.',
 S('print(~0~ and "yes" or "no")','yes','no|0','Zero is truthy in Lua.','nil|false'),
 S('print(~nil~ or "${word}")','${word}','nil|false','or evaluates the fallback for a falsey left operand.','true|${n}'),
 S('print(${n} ~==~ ${n})','true','false|nil','== tests equality of these numbers.','~=|<'),
 S('print(~not~ false)','true','false|nil','not converts truthiness to the opposite boolean.','#|-')),
 L('loops','Numeric and generic loops','Numeric for includes its endpoint. ipairs traverses sequential integer keys until the first absent value; break exits a loop.',
 S('local x = 0\nfor i = 1, ~${n}~ do x = x + 1 end\nprint(x)','${n}','${prev}|0','The numeric for loop includes both endpoints.','${prev}|0'),
 S('local x = 0\nfor i = 1, 5, ~2~ do x = x + 1 end\nprint(x)','3','5|2','A step of two visits 1, 3, and 5.','1|5'),
 S('local x = 0\nfor _, v in ~ipairs~({${n}, ${m}}) do x = x + v end\nprint(x)','${add}','${mul}|0','ipairs yields each sequential index and its value.','next|tonumber'),
 S('local x = 0\nwhile true do x = x + 1; ~break~ end\nprint(x)','1','0|Never terminates','break exits after one iteration.','return|goto')),
 L('functions','Functions and multiple returns','Functions are values. They can return multiple results. Assignment fills missing results with nil; parentheses around a call reduce it to one result.',
 S('local function f(x) return ~x + 1~ end\nprint(f(${n}))','${next}','${n}|nil','return passes the computed result to the caller.','x|nil'),
 S('local function f() return ${n}, ${m} end\nlocal a, b = ~f()~\nprint(b)','${m}','${n}|nil','An unparenthesized final call supplies both results.','(f())|nil'),
 S('local function f() return ${n}, ${m} end\nlocal a, b = ~(f())~\nprint(b)','nil','${m}|${n}','Parentheses adjust the call to one result, leaving b nil.','f()|${n}, ${m}'),
 S('local function count(...) return ~select~("#", ...) end\nprint(count(${n}, nil, ${m}))','3','2|1','select with # counts every supplied argument, including nil.','tonumber|type')),
 L('tables','Tables and absent values','Tables support named and integer keys. t.name abbreviates t["name"]. Assigning nil removes a key. Avoid # on tables with holes.',
 S('local t = {${n}, ${m}}\nprint(t[~1~])','${n}','${m}|nil','Sequence entries start at index one.','0|2'),
 S('local t = {name="${word}"}\nprint(t[~"name"~])','${word}','nil|name','Bracket syntax reads the string key name.','1|"other"'),
 S('local t = {x=${n}}\nt.x = ~nil~\nprint(t.x)','nil','${n}|0','Assigning nil removes the entry.','0|false'),
 S('local t = {${n}}\ntable.~insert~(t, ${m})\nprint(#t)','2','1|0','insert appends to this contiguous sequence.','remove|concat')),
 L('io','Input, files, and conversion','io.read may return nil at EOF. tonumber converts numeric strings; tostring converts values to text. Always close handles you open.',
 S('print(~tonumber~("${n}") + ${m})','${add}','${n}${m}|nil','tonumber explicitly converts digit text to a number.','type|string.len'),
 S('print(tonumber(~"bad"~))','nil','0|Error','Invalid numeric text converts to nil.','"${n}"|"0"'),
 S('local f = assert(io.open("notes.txt", "w"))\nf:write("${word}")\nf:~close~()','Writes text and closes the handle','Reads text only|Deletes the file','close releases the opened file handle.','flush|read','Assuming open succeeds, what happens?'),
 S('local line = nil\nprint(line ~or~ "${word}")','${word}','nil|false','or handles the nil value returned at EOF.','and|==')),
 L('scope','Local scope and modules','local limits a binding to its lexical scope. A module commonly returns a table. require caches loaded module results.',
 S('local x = ${n}\ndo local x = ${m} end\nprint(~x~)','${n}','${m}|nil','The inner local shadows rather than replaces the outer local.','nil|${m}'),
 S('local M = {}\nM.size = ${n}\n~return~ M','Exports the table as the chunk result','Creates a global named M|Prints the table','return provides the module value to its loader.','print|local','What does the last line do in a module chunk?'),
 S('local config = ~require~("config")','Loads or retrieves the cached module','Always reruns the file|Declares a global','require consults package.loaded before loading again.','dofile|loadfile','What behavior does this call provide?'),
 S('local x = ${n}\nlocal function f() return x end\nx = ${m}\nprint(f~()~)','${m}','${n}|nil','A closure reads its captured local variable after reassignment.','|[1]')),
 L('errors','Protected calls and assertions','error raises; pcall catches and returns a success flag followed by results or an error. assert raises for false or nil.',
 S('local ok = ~pcall~(function() error("${word}") end)\nprint(ok)','false','true|nil','pcall reports a caught error with false.','type|tostring'),
 S('local ok, value = pcall(function() return ~${n}~ end)\nprint(value)','${n}','true|nil','A successful protected call returns true followed by results.','nil|false'),
 S('~assert~(false, "${word}")','Raises an error','Returns false|Returns nil','assert raises when its first argument is falsey.','print|type','What happens?'),
 S('local ok, value = ~pcall~(function() return ${n} end)\nprint(ok)','true','false|${n}','The function completes normally, so the success flag is true.','tonumber|tostring')),
 L('references','References and table mutation','Assigning a table copies its reference, not its contents. rawequal compares identity without equality metamethods.',
 S('local a = {x=${n}}\nlocal b = ~a~\nb.x = ${m}\nprint(a.x)','${m}','${n}|nil','Both variables reference the same table.','{}|{x=${n}}'),
 S('local a = {x=${n}}\nlocal b = ~{x=a.x}~\nb.x = ${m}\nprint(a.x)','${n}','${m}|nil','This creates a separate table with a copied numeric field.','a|nil'),
 S('local a = {}\nprint(~rawequal~(a, a))','true','false|nil','The same table reference has identical identity.','tonumber|string.sub'),
 S('local a = {child={x=${n}}}\nlocal b = {child=a.child}\nb.child.x = ~${m}~\nprint(a.child.x)','${m}','${n}|nil','The outer tables differ but share the nested child.','${n}|nil')),
 L('metatables','Metatables and fallback lookup','Metatables customize operations. __index provides missing fields; __newindex handles assignment to absent keys. Raw operations bypass these hooks.',
 S('local t = setmetatable({}, {~__index~={size=${n}}})\nprint(t.size)','${n}','nil|0','__index supplies a fallback for the absent size key.','__newindex|__len'),
 S('local t = setmetatable({size=${m}}, {__index={size=${n}}})\nprint(~rawget~(t, "size"))','${m}','${n}|nil','rawget reads the actual table entry directly.','rawset|setmetatable'),
 S('local t = setmetatable({}, {~__len~=function() return ${n} end})\nprint(#t)','${n}','0|nil','__len overrides the length operation for this table.','__index|__call'),
 S('local t = setmetatable({}, {~__call~=function(_, x) return x+1 end})\nprint(t(${n}))','${next}','${n}|nil','__call lets a table behave as a callable object.','__len|__index')),
 L('methods','Colon methods and closures','Colon calls pass the receiver as self. Dot calls require that receiver explicitly. Factory functions can encapsulate state in an upvalue.',
 S('local t = {x=${n}}\nfunction t:get() return self.x end\nprint(t~:~get())','${n}','nil|Error','Colon syntax supplies t as self.','.|->'),
 S('local t = {x=${n}}\nfunction t.get(self) return self.x end\nprint(t.get(~t~))','${n}','nil|Error','A dot call passes the receiver explicitly here.','nil|${n}'),
 S('local function make()\n local x = ${n}\n return function() x=x+1; return x end\nend\nlocal f = ~make()~\nprint(f())','${next}','${n}|nil','The returned closure retains the private counter.','make|nil'),
 S('local x = ${n}\nlocal function f() x=x+1 end\n~f()~\nprint(x)','${next}','${n}|nil','The closure updates the captured local binding.','print(f)|type(f)')),
 L('coroutines','Coroutines and suspended execution','create makes a suspended coroutine; resume runs it; yield pauses with values. resume returns a success flag before yielded or returned results.',
 S('local co = coroutine.~create~(function() return ${n} end)\nprint(coroutine.status(co))','suspended','running|dead','Creating a coroutine does not execute its body.','wrap|resume'),
 S('local co = coroutine.create(function() coroutine.~yield~(${n}); return ${m} end)\nlocal ok, x = coroutine.resume(co)\nprint(x)','${n}','${m}|true','yield pauses the coroutine and provides the first result value.','resume|status'),
 S('local co = coroutine.create(function() return ${n} end)\ncoroutine.~resume~(co)\nprint(coroutine.status(co))','dead','suspended|running','A coroutine that returns normally is dead.','status|isyieldable'),
 S('local co = coroutine.create(function() error("${word}") end)\nlocal ok = coroutine.~resume~(co)\nprint(ok)','false','true|nil','resume reports an error with a false success flag.','status|running'))]

def php():
 return basics('php')+[
 L('strings','Strings and interpolation','PHP statements shown belong inside a <?php block. Double quotes interpolate variables; single quotes preserve their names. The dot operator concatenates strings.',
 S('$x = ${n};\necho ~"$x"~;','${n}','$x|x','Double quotes interpolate the variable value.','\'$x\'|"x"'),
 S('echo "${word}" ~.~ "${word}";','${joined}','${word}|Error','The dot operator concatenates text.','+|*'),
 S('echo ~strlen~("${word}");','${length}','0|${n}','strlen counts bytes; these words are ASCII.','strtoupper|strtolower'),
 S('echo ~strtoupper~("${word}");','${upper}','${word}|0','strtoupper returns uppercase text.','strtolower|strlen')),
 L('conditions','Comparison and truthiness','=== compares type and value; == permits coercion. The string "0" is falsey. ?? falls back only for null or an unset value.',
 S('echo (${n} ~===~ "${n}") ? "yes" : "no";','no','yes|Error','Strict equality rejects integer versus string.','==|!='),
 S('echo (~"0"~ ? "yes" : "no");','no','yes|0','The string zero is falsey in PHP.','"${word}"|${n}'),
 S('$x = null;\necho $x ~??~ "${word}";','${word}','null|Error','Null coalescing supplies the fallback for null.','&&|==='),
 S('$x = 0;\necho $x ~??~ ${n};','0','${n}|null','Null coalescing preserves zero because it is not null.','?:|+')),
 L('loops','Loops and foreach','for has initialization, condition, and update. foreach yields values or keys and values. break exits; continue skips an iteration.',
 S('$x=0;\nfor ($i=0; $i ~<~ ${n}; $i++) { $x++; }\necho $x;','${n}','${next}|0','The strict upper bound gives ${n} iterations.','<=|>'),
 S('$x=0;\n~foreach~ ([${n}, ${m}] as $v) { $x += $v; }\necho $x;','${add}','${mul}|0','foreach assigns each array value to v.','for|while'),
 S('$x=0;\nfor ($i=0; $i<3; $i++) { if ($i===1) ~continue~; $x++; }\necho $x;','2','1|3','continue skips only the middle iteration.','break|return'),
 S('$x=0;\nwhile (true) { $x++; ~break~; }\necho $x;','1','0|Never terminates','break exits the loop after one increment.','continue|return')),
 L('functions','Functions and typed parameters','Functions use return for results. Type declarations document and check contracts. Defaults fill missing arguments; named arguments bind by parameter name.',
 S('function bump(int $x): int { return ~$x + 1~; }\necho bump(${n});','${next}','${n}|0','return passes the computed integer to the caller.','$x|0'),
 S('function size($x=${n}) { return $x; }\necho ~size()~;','${n}','0|null','The omitted argument uses its default.','size(0)|size(null)'),
 S('function label($text) { return $text; }\necho label(~text: "${word}"~);','${word}','text|null','A named argument identifies the declared parameter.','other: "${word}"|text: null'),
 S('function change($x) { $x = ${m}; }\n$x=${n};\n~change($x)~;\necho $x;','${n}','${m}|0','This scalar parameter is passed by value.','$x=${m}|$x=0')),
 L('arrays','Arrays and keys','PHP arrays are ordered maps. [] appends; => associates keys and values. isset is false for missing and null values, while array_key_exists tests presence.',
 S('$a=[${n}, ${m}];\necho $a[~0~];','${n}','${m}|null','The first implicit integer key is zero.','1|2'),
 S('$a=["name" ~=>~ "${word}"];\necho $a["name"];','${word}','name|null','=> associates the string key with its value.','=|=='),
 S('$a=[${n}];\n$a~[]~=${m};\necho count($a);','2','1|0','Empty brackets append an element.','[0]|["0"]'),
 S('$a=["x"=>null];\necho ~array_key_exists~("x", $a) ? "yes" : "no";','yes','no|null','array_key_exists recognizes a key even when its value is null.','in_array|is_a')),
 L('io','Request values and basic I/O','Request data arrives as untrusted strings or arrays. Validate types before use. ?? provides defaults; htmlspecialchars escapes text for an HTML text context.',
 S('$_GET=[];\necho $_GET["name"] ~??~ "${word}";','${word}','name|Error','The absent request key uses a fallback.','+|==='),
 S('echo ~intval~("${n}") + ${m};','${add}','${n}${m}|0','intval converts digit text to an integer.','strlen|strtoupper'),
 S('echo htmlspecialchars(~"<b>"~, ENT_QUOTES, "UTF-8");','&lt;b&gt;','<b>|b','HTML escaping prevents this text from being interpreted as a tag.','"b"|"&lt;b&gt;"'),
 S('$h=fopen("notes.txt", "w");\nif ($h !== false) { fwrite($h, "${word}"); ~fclose~($h); }','Writes and closes when open succeeds','Always reads a file|Leaves the handle open','The handle is checked and closed after writing.','fflush|fread','What does this snippet do?')),
 L('namespaces','Namespaces and loading','Namespaces qualify names and avoid collisions. use introduces an alias. require_once loads a file only once and fails if it cannot be loaded.',
 S('namespace App;\nconst SIZE=${n};\necho ~SIZE~;','${n}','App|0','An unqualified constant resolves inside the current namespace.','__NAMESPACE__|0'),
 S('namespace App;\necho ~__NAMESPACE__~;','App','PHP|Empty string','__NAMESPACE__ gives the current namespace name.','__LINE__|__FILE__'),
 S('~require_once~ "config.php";','Loads the file at most once','Always reloads the file|Silently ignores a missing required file','require_once both requires the file and prevents repeated inclusion.','include|require','Which inclusion rule applies?'),
 S('namespace App;\nuse DateTimeImmutable ~as~ Clock;\n$x = new Clock();','Clock aliases DateTimeImmutable','Creates a subclass named Clock|Renames the original class globally','as provides a local import alias.','extends|implements','What is the role of Clock?')),
 L('errors','Exceptions and cleanup','throw raises an exception. catch selects handlers; finally runs even during exception propagation. TypeError implements Throwable.',
 S('try { throw new RuntimeException(); } ~catch~ (RuntimeException $e) { echo "${word}"; }','${word}','Exception escapes|null','catch handles the matching exception.','finally|else'),
 S('try { echo ${n}; } ~finally~ { echo ${m}; }','${n}${m}','${n}|${m}','finally runs after the try body.','catch|else'),
 S('~throw~ new InvalidArgumentException("${word}");','Raises an exception','Returns a string|Prints a string','throw transfers control to an exception handler.','echo|return','What happens?'),
 S('try { strlen([]); } catch (~Throwable~ $e) { echo ${n}; }','${n}','0|null','Throwable catches TypeError as well as Exception subclasses.','Exception|RuntimeException')),
 L('objects','Classes and instance state','Constructors initialize objects. -> accesses members; private restricts access. Typed properties describe state without changing ordinary object identity.',
 S('class Box { public function __construct(public int $size) {} }\necho (new Box(${n}))~->~size;','${n}','0|null','-> reads an instance property.','::|.'),
 S('class Box { private int $x=${n}; public function get(): int { return ~$this->x~; } }\necho (new Box())->get();','${n}','null|0','The method can access its own private instance property.','$x|self::x'),
 S('class Box { public int $x=${n}; }\n$a=new Box(); $b=~$a~; $b->x=${m};\necho $a->x;','${m}','${n}|null','Object assignment shares the same object handle.','clone $a|new Box()'),
 S('class Box { public int $x=${n}; }\n$a=new Box(); $b=~clone $a~; $b->x=${m};\necho $a->x;','${n}','${m}|null','clone makes a distinct object with copied properties.','$a|$a->x')),
 L('contracts','Interfaces, traits, and enums','Interfaces specify contracts. Traits share implementation. Backed enum cases carry scalar values; they are not interchangeable with those raw values.',
 S('interface Sized { public function size(): int; }\nclass Box ~implements~ Sized { public function size(): int { return ${n}; } }\necho (new Box())->size();','${n}','0|null','implements declares that Box satisfies the interface.','extends|uses'),
 S('trait Label { public function label() { return "${word}"; } }\nclass Box { ~use~ Label; }\necho (new Box())->label();','${word}','null|Label','use inserts the trait implementation into the class.','extends|include'),
 S('enum Status: string { case Ready="${word}"; }\necho Status::Ready->~value~;','${word}','Ready|null','value exposes the backed enum scalar.','name|status'),
 S('enum Status: string { case Ready="${word}"; }\necho Status::Ready->~name~;','Ready','${word}|Status','name exposes the case identifier.','value|status')),
 L('closures','Closures and capture','Anonymous functions explicitly capture with use; & captures by reference. Arrow functions capture referenced outer values by value automatically.',
 S('$x=${n}; $f=function() use (~$x~) { return $x; }; $x=${m};\necho $f();','${n}','${m}|null','Value capture preserves the value at closure creation.','&$x|$other'),
 S('$x=${n}; $f=function() use (~&$x~) { return $x; }; $x=${m};\necho $f();','${m}','${n}|null','Reference capture follows subsequent changes to the variable.','$x|$other'),
 S('$x=${n}; $f=~fn($y) => $x + $y~;\necho $f(${m});','${add}','${mul}|null','An arrow function implicitly captures the outer x by value.','fn($y) => $x * $y|fn($y) => $y'),
 S('$x=${n}; $f=fn() => $x; $x=${m};\necho ~$f()~;','${n}','${m}|null','The arrow function retained the earlier scalar value.','$x|0')),
 L('generators','Generators and reference pitfalls','yield makes a function lazy. foreach consumes yielded values. A by-reference foreach variable remains a reference after the loop until unset.',
 S('function items() { ~yield~ ${n}; yield ${m}; }\necho items()->current();','${n}','${m}|null','The first yield supplies the current generator value.','return|echo'),
 S('function items() { yield "name" ~=>~ "${word}"; }\nforeach(items() as $k=>$v) { echo $k; }','name','${word}|0','A keyed yield exposes the specified key.','=|=='),
 S('$a=[${n}]; foreach($a as &$v) {}\n~unset($v)~; $v=${m};\necho $a[0];','${n}','${m}|null','unset breaks the lingering reference before reassignment.','$v=0|print($v)'),
 S('$a=[${n}]; $b=$a; $b[0]=~${m}~;\necho $a[0];','${n}','${m}|null','Ordinary array assignment has value semantics here.','${n}|0'))]

def perl():
 return basics('perl')+[
 L('strings','Strings, sigils, and interpolation','Scalars use $. Double quotes interpolate; single quotes preserve literal text. A dot concatenates strings; x repeats them. Assume use strict and use warnings.',
 S('my $x=${n}; print ~"$x"~;','${n}','$x|x','Double quotes interpolate the scalar value.','\'$x\'|"x"'),
 S('print "${word}" ~.~ "${word}";','${joined}','${word}|0','The dot operator concatenates strings.','+|=='),
 S('print ~length~("${word}");','${length}','0|${n}','length counts characters in this ASCII string.','uc|lc'),
 S('print "${word}" ~x~ 2;','${joined}','${word}|0','x repeats the string twice.','+|eq')),
 L('conditions','Numeric and string comparison','eq compares strings; == compares numbers. undef, empty text, zero, and "0" are falsey. // falls back only for undefined values.',
 S('print("${word}" ~eq~ "${word}" ? "yes" : "no");','yes','no|undef','eq checks string equality.','ne|lt'),
 S('print(~"0"~ ? "yes" : "no");','no','yes|0','The string zero is falsey in Perl.','"${word}"|${n}'),
 S('my $x=undef; print $x ~//~ "${word}";','${word}','undef|0','Defined-or uses its fallback for undef.','&&|eq'),
 S('my $x=0; print $x ~//~ ${n};','0','${n}|undef','Defined-or preserves zero because it is defined.','|||+')),
 L('loops','Loops and loop controls','for can iterate a list; next skips an iteration and last exits. The range operator .. includes both integer endpoints in list context.',
 S('my $x=0; for my $i (1~..~${n}) { $x++; } print $x;','${n}','${prev}|0','The range includes every integer from one through ${n}.','+|,'),
 S('my $x=0; ~for~ my $v (${n}, ${m}) { $x+=$v; } print $x;','${add}','${mul}|0','The loop visits both listed values.','while|if'),
 S('my $x=0; for my $i (0..2) { ~next~ if $i==1; $x++; } print $x;','2','1|3','next skips only the middle iteration.','last|return'),
 S('my $x=0; while (1) { $x++; ~last~; } print $x;','1','0|Never terminates','last exits the loop after one increment.','next|redo')),
 L('subroutines','Subroutines and arguments','Arguments arrive in @_. A return supplies results; list assignment commonly names parameters. Scalar arguments can alias caller variables through @_.',
 S('sub bump { my ($x)=@_; return ~$x+1~; } print bump(${n});','${next}','${n}|undef','List assignment copies the first argument to the local x.','$x|0'),
 S('sub add { my ($a,$b)=~@_~; return $a+$b; } print add(${n},${m});','${add}','${mul}|0','@_ contains the argument list for the current call.','@ARGV|()'),
 S('sub stop { ~return~ ${n}; ${m}; } print stop();','${n}','${m}|undef','return exits before the later expression.','print|warn'),
 S('sub change { ~$_[0]~=${m}; } my $x=${n}; change($x); print $x;','${m}','${n}|undef','The argument slot aliases the caller scalar in this call.','my $x|my $other')),
 L('collections','Arrays, hashes, and sigils','@ names an array and % a hash; a single element uses $. Arrays start at zero. Hash keys are strings; exists tests presence even if the value is undef.',
 S('my @a=(${n},${m}); print $a[~0~];','${n}','${m}|undef','A scalar array element uses $ and zero-based indexing.','1|2'),
 S('my %h=(name ~=>~ "${word}"); print $h{name};','${word}','name|undef','The fat comma pairs this key with its value.','=|=='),
 S('my @a=(${n}); ~push~ @a, ${m}; print scalar @a;','2','1|0','push appends to the array.','shift|pop'),
 S('my %h=(x=>undef); print(~exists~ $h{x} ? "yes" : "no");','yes','no|undef','exists tests whether the hash entry is present.','defined|ref')),
 L('io','Handles, lines, and conversion','Use lexical filehandles and three-argument open. Check open failure and close handles. chomp removes a trailing input record separator; <> reads a record.',
 S('my $x="${word}\n"; ~chomp~ $x; print $x;','${word}','${word}\n|Empty string','chomp removes the final newline from this scalar.','chop|undef'),
 S('print ~int~(${n} / ${m});','${div}','${rem}|${mul}','int truncates the positive fractional quotient.','length|uc'),
 S('open my $fh, ">", "notes.txt" or die $!;\nprint {$fh} "${word}";\n~close~ $fh;','Writes text and closes the handle','Only reads text|Prints to standard output','The explicit handle receives text and is then closed.','undef|readline','Assuming open succeeds, what happens?'),
 S('my $line=undef; print $line ~//~ "${word}";','${word}','undef|0','The defined-or fallback handles the EOF-like undef value.','&&|eq')),
 L('modules','Packages and lexical declarations','package changes the namespace; my creates lexical variables and our declares package variables. use loads a module during compilation. Traditional modules return a true value.',
 S('package Config; our $size=${n};\npackage main; print ~$Config::size~;','${n}','0|undef','The qualified name accesses a package variable.','$main::size|0'),
 S('my $x=${n}; { my $x=${m}; } print ~$x~;','${n}','${m}|undef','The inner lexical binding shadows the outer one temporarily.','${m}|0'),
 S('~use~ strict;','Enables compile-time restrictions','Disables warnings|Creates a variable','use strict catches undeclared symbolic usage and other unsafe constructs.','no|print','What does this declaration do?'),
 S('package Config;\nsub size { ${n} }\n~1~;','Returns a true module value','Returns false|Prints one','A traditional require-loaded module must finish with a true value.','0|undef','Why end a traditional module this way?')),
 L('errors','die, eval, and error state','die throws an exception. Block eval catches it and stores the message in $@. A successful final true expression distinguishes success from a false result.',
 S('my $ok=eval { die "${word}"; 1 }; print(~defined~ $ok ? "yes" : "no");','no','yes|${word}','A dying eval returns undef.','ref|length'),
 S('eval { die "${word}\n"; }; print ~$@~;','${word}\n','Empty string|0','After failure, $@ contains the exception text.','$!|$_'),
 S('my $ok=~eval~ { ${n}; 1 }; print $ok;','1','${n}|undef','The final true value signals successful completion.','do|sub'),
 S('~die~ "${word}\n";','Raises an exception','Prints to stdout and continues|Returns zero','die interrupts normal control flow.','print|warn','What happens without an enclosing eval?')),
 L('references','References and dereferencing','Backslash creates a reference; -> dereferences for members. Anonymous [] and {} create references. Assignment of a reference shares the referent.',
 S('my $a=[${n},${m}]; print $a~->[0]~;','${n}','${m}|undef','Arrow indexing dereferences the array reference.','->[1]|->[2]'),
 S('my $h={name=>"${word}"}; print $h~->{name}~;','${word}','name|undef','Arrow braces read a hash reference entry.','->{other}|->[0]'),
 S('my $a=[${n}]; my $b=~$a~; $b->[0]=${m}; print $a->[0];','${m}','${n}|undef','Both scalars contain references to the same array.','[${n}]|[]'),
 S('my $a=[${n}]; print ~ref~($a);','ARRAY','HASH|SCALAR','ref identifies the referent type.','length|scalar')),
 L('context','Scalar and list context','Context changes how expressions produce values. An array in scalar context yields its length. List assignment, scalar assignment, and wantarray expose this distinction.',
 S('my @a=(${n},${m}); my $x=~@a~; print $x;','2','${n}|${m}','Scalar assignment asks the array for its element count.','$a[0]|$a[1]'),
 S('my @a=(${n},${m}); my @b=~@a~; print $b[0];','${n}','2|${m}','List assignment copies the array elements.','scalar @a|()'),
 S('sub mode { return ~wantarray~ ? "list" : "scalar"; } my $x=mode(); print $x;','scalar','list|undef','wantarray is false for a scalar-context call.','1|"yes"'),
 S('my %h=(a=>${n},b=>${m}); print scalar ~keys~ %h;','2','${add}|0','keys in scalar context gives the number of hash entries.','each|values')),
 L('regex','Regular expressions and captures','=~ binds a match or substitution to a string. Parentheses capture substrings, anchors constrain position, and /g repeats substitutions.',
 S('my $x="id${n}"; $x =__TILDE__ /id(~\\d+~)/; print $1;','${n}','id|undef','The parenthesized digit pattern captures the numeric suffix.','[a-z]+|z+'),
 S('my $x="${word}"; $x =__TILDE__ ~s/^/pre-/~; print $x;','pre-${word}','${word}|pre-','^ matches the start, so the substitution inserts a prefix.','s/$/pre-/|s/./pre-/'),
 S('my $x="a-a"; $x =__TILDE__ s/a/b/~g~; print $x;','b-b','b-a|a-b','The global modifier replaces both occurrences.','i|m'),
 S('print("x${n}" =__TILDE__ ~/^\\d+$/~ ? "yes" : "no");','no','yes|undef','Both anchors require the entire string to contain only digits.','/\\d+/|/x/')),
 L('objects','Objects, methods, and closures','bless associates a reference with a class. A method call passes the receiver first. Closures retain lexical state after the creating call returns.',
 S('package Box; sub new { my ($class)=@_; ~bless~ {x=>${n}}, $class }\npackage main; print Box->new->{x};','${n}','undef|Box','bless turns this hash reference into an object of the requested class.','ref|scalar'),
 S('package Box; sub size { my ($self)=@_; return $self->{x}; }\npackage main; my $b=bless {x=>${n}}, "Box"; print $b~->size()~;','${n}','undef|0','Method syntax supplies the object as the first argument.','->{size}|->{other}'),
 S('my $x=${n}; my $f=~sub { $x+1 }~; print $f->();','${next}','${n}|undef','An anonymous subroutine closes over the lexical x.','sub { $x }|sub { 0 }'),
 S('my $x=${n}; my $f=sub { $x }; $x=${m}; print ~$f->()~;','${m}','${n}|undef','The closure observes the updated lexical variable.','$x+1|0'))]

def build():
 from build import DERIVED
 DERIVED['m_double']='m*2'
 emit('ruby','Ruby','Ruby 3.x', [source('ruby','Ruby in Twenty Minutes','https://www.ruby-lang.org/en/documentation/quickstart/'),source('ruby-doc','Ruby syntax reference','https://docs.ruby-lang.org/en/master/syntax_rdoc.html')],ruby())
 emit('lua','Lua','Lua 5.4', [source('lua','Lua 5.4 Reference Manual','https://www.lua.org/manual/5.4/')],lua())
 emit('php','PHP','PHP 8.2+; snippets are inside a PHP block', [source('php','PHP language reference','https://www.php.net/manual/en/langref.php')],php())
 emit('perl','Perl','Perl 5; strict and warnings enabled; snippets omit those declarations', [source('perl','Perl introduction and tutorials','https://perldoc.perl.org/perlintro'),source('perlref','Perl reference tutorial','https://perldoc.perl.org/perlreftut')],perl())
