from build import S,lesson as L


def lessons():
 return [
 L('objects','Figure, Axes, and artists','A Figure owns the overall canvas; an Axes owns one plotting region. Lines, text, images, and patches are artists attached to these objects. Prefer explicit fig/ax references over relying on the implicit current plot. All code can use a noninteractive backend.',
 S('fig,ax=plt.~subplots~()\nprint(len(fig.axes))','1','0|2','subplots creates a figure containing one Axes by default.','figure|axes'),
 S('fig,ax=plt.subplots()\nprint(~ax.figure is fig~)','True','False|None','The Axes retains a reference to its owning Figure.','ax is fig|ax.figure is None'),
 S('fig,ax=plt.subplots()\nax.plot([0,1],[0,${n}])\nprint(len(~ax.lines~))','1','2|0','plot adds one Line2D artist for this pair of vectors.','fig.axes|ax.collections'),
 S('fig,ax=plt.subplots()\nax.~set_title~("${word}")\nprint(ax.get_title())','${word}','Empty string|AttributeError','The title is text belonging to this Axes.','set_xlabel|set_ylabel')),
 L('lines','Line data and artist properties','plot pairs x and y coordinates and returns a list of lines. A label is metadata used by legends; it does not change the data. Line properties can be supplied on creation or changed through the returned artist.',
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[${n},${m}])\nprint(line.~get_ydata()~.tolist())','[${n}, ${m}]','[0, 1]|[]','The returned Line2D stores the supplied y coordinates.','get_xdata()|get_label()'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,${n}],label=~"${word}"~)\nprint(line.get_label())','${word}','Empty string|${n}','label names the series without altering its coordinates.','"other"|""'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,${n}],linewidth=~2~)\nprint(line.get_linewidth())','2.0','1.0|${n}.0','linewidth is a display property measured in points.','1|3'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,${n}])\nline.~set_color~("red")\nprint(line.get_color())','red','blue|AttributeError','A setter updates the artist property after creation.','set_label|set_marker')),
 L('scatter','Scatter plots and collections','scatter creates a PathCollection rather than Line2D. Its s argument specifies marker area in points squared. Offsets hold the data positions. Color values may be literal colors or numbers mapped through a colormap.',
 S('fig,ax=plt.subplots()\npoints=ax.~scatter~([0,1],[${n},${m}])\nprint(points.get_offsets().shape)','(2, 2)','(2,)|(1, 2)','The collection stores two x/y coordinate pairs.','plot|bar'),
 S('fig,ax=plt.subplots()\npoints=ax.scatter([0],[${n}],s=~36~)\nprint(int(points.get_sizes()[0]))','36','6|${n}','s is area, not radius or diameter.','6|12'),
 S('fig,ax=plt.subplots()\nax.scatter([0],[${n}])\nprint(len(~ax.collections~))','1','0|2','Scatter adds a collection to the Axes.','ax.lines|ax.texts'),
 S('fig,ax=plt.subplots()\npoints=ax.scatter([0,1],[${n},${m}])\npoints.~set_offsets~([[2,3]])\nprint(points.get_offsets().shape)','(1, 2)','(2, 2)|(2,)','Replacing offsets changes the stored point positions.','set_sizes|set_array')),
 L('labels','Labels, legends, and annotations','Axis labels describe coordinates; titles describe panels. A legend uses labeled artists. Annotation text can be positioned independently from the referenced data location. Good labels clarify units and quantities without modifying the plotted data.',
 S('fig,ax=plt.subplots()\nax.~set_xlabel~("${word}")\nprint(ax.get_xlabel())','${word}','Empty string|AttributeError','This labels the horizontal axis.','set_ylabel|set_title'),
 S('fig,ax=plt.subplots()\nax.plot([0,1],[0,${n}],label="${word}")\nlegend=ax.~legend~()\nprint(legend.get_texts()[0].get_text())','${word}','Empty string|AttributeError','legend collects the labeled line.','get_legend|text'),
 S('fig,ax=plt.subplots()\ntext=ax.~annotate~("${word}",xy=(0,${n}))\nprint(text.get_text())','${word}','${n}|AttributeError','annotate attaches text to a specified reference location.','set_title|set_xlabel'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[${n},${m}])\nax.set_ylabel("changed")\nprint(line.~get_ydata()~.tolist())','[${n}, ${m}]','[0, 1]|[]','Changing a label leaves the underlying coordinates intact.','get_xdata()|get_label()')),
 L('panels','Subplots, grids, and axis sharing','subplots can return a scalar Axes or an array, depending on grid size and squeeze. squeeze=False makes the axes container predictably two-dimensional. Shared axes coordinate limits across panels. Use fig.suptitle for a whole-figure heading.',
 S('fig,axes=plt.subplots(2,3)\nprint(~axes.shape~)','(2, 3)','(6,)|(3, 2)','The default array mirrors the requested row/column grid.','axes.size|len(fig.axes)'),
 S('fig,axes=plt.subplots(1,1,squeeze=~False~)\nprint(axes.shape)','(1, 1)','()|AttributeError','Disabling squeezing retains a two-dimensional axes array.','True|None'),
 S('fig,axes=plt.subplots(2,1,sharex=~True~)\naxes[0].set_xlim(0,${n})\nprint(tuple(map(float,axes[1].get_xlim())))','(0.0, ${n}.0)','(0.0, 1.0)|(1.0, 0.0)','Shared x limits propagate to the other panel.','False|"none"'),
 S('fig,axes=plt.subplots(1,2)\ntext=fig.~suptitle~("${word}")\nprint(text.get_text())','${word}','Empty string|AttributeError','suptitle belongs to the Figure rather than one panel.','get_suptitle|title')),
 L('limits','Limits, scales, and ticks','Limits control the visible range; scales transform the axis mapping. Logarithmic scales need meaningful positive data. Ticks specify positions and labels. Zooming changes the view, not the stored points.',
 S('fig,ax=plt.subplots()\nax.~set_xlim~(0,${n})\nprint(tuple(map(float,ax.get_xlim())))','(0.0, ${n}.0)','(0.0, 1.0)|(${n}.0, 0.0)','set_xlim sets the visible horizontal interval.','set_ylim|set_xticks'),
 S('fig,ax=plt.subplots()\nax.~set_xscale~("log")\nprint(ax.get_xscale())','log','linear|AttributeError','The scale controls how coordinates map onto the axis.','set_xlabel|set_title'),
 S('fig,ax=plt.subplots()\nax.set_xticks(~[0,${n}]~)\nprint(ax.get_xticks().tolist())','[0, ${n}]','[0, 1]|[]','The positions are data coordinates; labels can be configured separately.','[0,1]|[]'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[${n},${m}])\nax.set_ylim(0,1)\nprint(line.~get_ydata()~.tolist())','[${n}, ${m}]','[0, 1]|[]','Clipping the visible range leaves the line data unchanged.','get_xdata()|get_label()')),
 L('bars','Bars, histograms, and counts','bar plots values at specified positions; hist computes bin counts from samples. Histogram edges define the intervals, with the final right edge included. Interpret returned counts and edges rather than assuming a picture proves a distribution claim.',
 S('fig,ax=plt.subplots()\nbars=ax.~bar~([0,1],[${n},${m}])\nprint(len(bars))','2','1|0','Each input pair creates one bar patch.','plot|scatter'),
 S('fig,ax=plt.subplots()\nbars=ax.bar([0],[${n}])\nprint(int(bars[0].~get_height()~))','${n}','0|1','The patch height reflects the supplied bar value.','get_width()|get_x()'),
 S('fig,ax=plt.subplots()\ncounts,edges,_=ax.hist([0,0,1],bins=~[-0.5,0.5,1.5]~)\nprint(counts.tolist())','[2.0, 1.0]','[1.0, 2.0]|[3.0]','The first bin contains two zeros and the second one one.','[-0.5,1.5]|[0.5,1.5]'),
 S('fig,ax=plt.subplots()\ncounts,edges,_=ax.hist([0,1,2],bins=~2~)\nprint(len(edges))','3','2|4','Two bins require three boundaries.','1|3')),
 L('images','Images, colormaps, and colorbars','imshow maps an array to an image artist. Numeric values can map through a colormap and normalization; a colorbar explains that mapping. Origin and extent control spatial interpretation. A colorbar creates its own Axes in a simple figure.',
 S('fig,ax=plt.subplots()\nimg=ax.~imshow~([[${n},0],[${m},1]])\nprint(img.get_array().shape)','(2, 2)','(4,)|(1, 4)','The image artist stores the two-dimensional data.','plot|scatter'),
 S('fig,ax=plt.subplots()\nimg=ax.imshow([[0,1]],cmap=~"viridis"~)\nprint(img.get_cmap().name)','viridis','gray|AttributeError','cmap selects the numeric-to-color palette.','"gray"|"plasma"'),
 S('fig,ax=plt.subplots()\nimg=ax.imshow([[0,${n}]],vmin=0,vmax=~${n}~)\nprint(img.get_clim())','(0.0, ${n}.0)','(0.0, 1.0)|None','The color limits define the normalization endpoints.','1|100'),
 S('fig,ax=plt.subplots()\nimg=ax.imshow([[0,1]])\nfig.~colorbar~(img,ax=ax)\nprint(len(fig.axes))','2','1|0','The colorbar adds a second Axes beside the data Axes.','suptitle|legend')),
 L('coordinates','Data and axes coordinate systems','Transform objects specify how coordinates are interpreted. ax.transData uses data units; ax.transAxes uses fractions of the panel. An annotation may reference a data point but offset its text in points. Mixing coordinate systems intentionally makes stable labels.',
 S('fig,ax=plt.subplots()\nt=ax.text(0.5,0.5,"${word}",transform=~ax.transAxes~)\nprint(t.get_transform() is ax.transAxes)','True','False|AttributeError','Axes fractions keep this text at the panel center when limits change.','ax.transData|fig.transFigure'),
 S('fig,ax=plt.subplots()\nt=ax.text(${n},0,"${word}",transform=~ax.transData~)\nprint(t.get_position())','(${n}, 0)','(0.5, 0.5)|(0, 0)','Data coordinates tie the text to the plotted quantity.','ax.transAxes|fig.transFigure'),
 S('fig,ax=plt.subplots()\nt=ax.annotate("${word}",xy=(0,0),xytext=(5,5),textcoords=~"offset points"~)\nprint(t.get_text())','${word}','Empty string|ValueError','The text is offset from the reference point in display points.','"invalid"|"unknown"'),
 S('fig,ax=plt.subplots()\nline=ax.~axhline~(${n})\nprint(list(line.get_ydata()))','[${n}, ${n}]','[0, 1]|[${n}]','axhline holds y in data units while spanning axes-fraction x positions.','axvline|plot')),
 L('styles','Scoped styles and reusable presentation','rcParams control defaults for new artists. rc_context temporarily changes defaults and restores them on exit. Existing artists generally keep their assigned properties. Keep styling separate from data preparation so reusable plotting functions remain predictable.',
 S('with plt.~rc_context~({"lines.linewidth":3}):\n    fig,ax=plt.subplots()\n    line,=ax.plot([0,1],[0,${n}])\n    print(line.get_linewidth())','3.0','1.0|0.0','The context supplies a temporary default for the new line.','style.use|figure'),
 S('before=plt.rcParams["lines.linewidth"]\nwith plt.rc_context({"lines.linewidth":7}):\n    pass\nprint(plt.rcParams["lines.linewidth"]~==before~)','True','False|None','rc_context restores the earlier value after the block.','==7|is None'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,${n}],alpha=~0.5~)\nprint(line.get_alpha())','0.5','1.0|None','alpha controls artist opacity without rescaling its numeric data.','1.0|None'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,${n}],linestyle=~"--"~)\nprint(line.get_linestyle())','--','-|None','The line style changes the drawn stroke pattern.','"-"|"None"')),
 L('updates','Updating artists and autoscaling','Reusing artists avoids accumulating duplicates during repeated updates. set_data changes a line but does not always recompute limits. relim recomputes data limits and autoscale_view updates the view. Test artist counts and values to catch plotting-state mistakes.',
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,1])\nline.~set_ydata~([${n},${m}])\nprint(list(line.get_ydata()))','[${n}, ${m}]','[0, 1]|[]','Update the existing line instead of creating another one.','set_xdata|set_label'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,1])\nline.set_ydata([${n},${m}])\nprint(len(~ax.lines~))','1','2|0','Changing data on one artist does not add a new line.','ax.collections|ax.patches'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,1])\nline.~remove~()\nprint(len(ax.lines))','0','1|2','Removing an artist detaches it from the Axes.','get_label|get_color'),
 S('fig,ax=plt.subplots()\nline,=ax.plot([0,1],[0,${n}])\nax.~clear~()\nprint(len(ax.lines))','0','1|2','clear removes plot content from this Axes; the Figure still exists.','relim|autoscale_view')),
 L('export','Saving, closing, and testing figures','Save through the explicit Figure to avoid exporting the wrong current figure. dpi and figsize determine raster pixel dimensions. Vector formats preserve supported vector elements. Close finished figures in batch jobs. Tests can inspect artists without opening a GUI.',
 S('import io\nfig,ax=plt.subplots()\nax.plot([0,1],[0,${n}])\nout=io.BytesIO()\nfig.~savefig~(out,format="png")\nprint(out.getvalue().startswith(b"\\x89PNG"))','True','False|AttributeError','savefig writes a PNG into the in-memory binary buffer.','show|clear'),
 S('fig,ax=plt.subplots(figsize=(4,3),dpi=~100~)\nprint(tuple(fig.canvas.get_width_height()))','(400, 300)','(4, 3)|(300, 400)','In a standard noninteractive canvas, inches times dpi yields pixel dimensions.','50|200'),
 S('fig,ax=plt.subplots()\nnumber=fig.number\nplt.~close~(fig)\nprint(plt.fignum_exists(number))','False','True|None','Closing removes this figure from pyplot management.','figure|show'),
 S('fig,ax=plt.subplots()\nax.plot([0,1],[0,${n}])\nassert len(ax.lines)==~1~\nprint("ready")','ready','AssertionError|AttributeError','Inspecting artists provides a deterministic structural test without visual guessing.','0|2')),
 ]
