from build import S,lesson as L


def lessons():
 result=[
 L('arrays','Array creation and structural metadata','An ndarray has a shape, a rank (ndim), an element count (size), and one dtype. A shape tuple names axis lengths in order. Use explicit dtypes when representation matters. These exercises print Python lists or scalar values to avoid version-dependent array formatting.',
 S('a=np.array([[${n},${m}],[0,1]])\nprint(~a.shape~)','(2, 2)','(4,)|(2,)','shape reports two rows and two columns.','a.size|a.ndim'),
 S('a=np.zeros((2,${m}))\nprint(~a.ndim~)','2','${m}|1','ndim counts axes, not elements along an axis.','a.size|a.shape'),
 S('a=np.ones((2,${m}))\nprint(~a.size~)','${twom}','2|${m}','size is the product of all axis lengths.','a.ndim|a.shape'),
 S('a=np.array([${n}],dtype=~np.float64~)\nprint(a.dtype.name)','float64','int64|bool','An explicit dtype makes this array floating point.','np.int64|bool')),
 L('creation','Ranges, grids, and initialization','arange uses a step and excludes the endpoint. linspace specifies a number of evenly spaced samples and includes the endpoint by default. zeros, ones, and full initialize values; empty does not promise initialized numeric contents.',
 S('print(np.arange(~${n}~).size)','${n}','${next}|0','A positive single argument produces integers from zero to ${prev}.','${next}|0'),
 S('print(np.linspace(0,${n},num=~3~).size)','3','${n}|2','num controls the sample count independently of endpoint values.','2|4'),
 S('a=np.full((2,),~${n}~)\nprint(a.tolist())','[${n}, ${n}]','[0, 0]|[${n}]','full fills every element with the supplied value.','0|${m}'),
 S('a=np.empty(3)\nprint(~a.shape~)','(3,)','(0,)|(1, 3)','empty allocates the requested shape; reading its uninitialized numbers is not a predictable output exercise.','a.ndim|a.size')),
 L('indexing','Indices, slices, and axis selection','A comma separates indexing operations on different axes. Integer indexing removes an axis; a slice preserves it. Negative indices count from the end. Basic slices generally share storage with their source.',
 S('a=np.array([[${n},0],[${m},1]])\nprint(int(a[~1,0~]))','${m}','${n}|1','Row one, column zero selects the lower-left element.','0,0|1,1'),
 S('a=np.zeros((3,4))\nprint(a[~0~].shape)','(4,)','(1, 4)|(3, 4)','An integer row index removes the first axis.','0:1|:'),
 S('a=np.zeros((3,4))\nprint(a[~0:1~].shape)','(1, 4)','(4,)|(3, 4)','A one-row slice retains the row axis.','0|:'),
 S('a=np.array([${n},${m}])\nprint(int(a[~-1~]))','${m}','${n}|IndexError','The negative index selects the final element.','0|2')),
 L('operations','Elementwise operations and comparisons','Arithmetic on arrays usually acts elementwise, not as matrix multiplication. Comparisons produce boolean arrays. Use elementwise logical operators with parentheses; Python and/or try to interpret a whole array as one truth value.',
 S('a=np.array([${n},${m}])\nprint((a~+1~).tolist())','[${next}, ${mnext}]','[${n}, ${m}]|[1, 1]','Scalar addition applies to each element.','*0|+0'),
 S('a=np.array([${n},0])\nprint((a~>0~).tolist())','[True, False]','[True, True]|[False, True]','Comparison tests each element independently.','>=0|<0'),
 S('a=np.array([${n},0])\nprint(~np.count_nonzero(a)~)','1','2|0','count_nonzero counts nonzero entries without a Python truth test on the array.','a.size|a.ndim-1'),
 S('a=np.array([${n},0])\nprint(((a>0) ~&~ (a<100)).tolist())','[True, False]','[True, True]|ValueError','Parenthesized conditions combine elementwise with bitwise-and syntax.','or|and')),
 L('reductions','Reductions, axes, and keepdims','A reduction removes its chosen axis unless keepdims retains a length-one axis. On a 2D table, axis=0 combines rows and axis=1 combines columns. Explicit axes avoid accidental aggregation across a batch or feature dimension.',
 S('a=np.array([[${n},0],[${m},1]])\nprint(a.sum(axis=~0~).tolist())','[${add}, 1]','[${n}, ${mnext}]|${add1}','Axis zero combines rows, leaving one result per column.','1|None'),
 S('a=np.array([[${n},0],[${m},1]])\nprint(a.sum(axis=~1~).tolist())','[${n}, ${mnext}]','[${add}, 1]|${add1}','Axis one combines columns, leaving one result per row.','0|None'),
 S('a=np.zeros((2,3))\nprint(a.sum(axis=1,keepdims=~True~).shape)','(2, 1)','(2,)|(1, 3)','keepdims keeps the reduced axis so later broadcasting is explicit.','False|None'),
 S('a=np.array([${n},0])\nprint(bool(~np.any(a>0)~))','True','False|ValueError','any reduces a boolean array to whether at least one element is true.','np.all(a>0)|a>0')),
 L('broadcasting','Broadcasting without accidental axes','NumPy aligns shapes from the right. Dimensions are compatible when equal or one; missing leading dimensions act as ones. Broadcasting avoids explicit repetition, but a misplaced singleton axis can create a much larger output than intended.',
 S('a=np.zeros((2,3)); b=np.ones(3)\nprint((~a+b~).shape)','(2, 3)','(3, 2)|(6,)','The length-three vector broadcasts across rows.','a.T+b[:,None]|a.ravel()'),
 S('a=np.zeros((2,1)); b=np.ones((1,3))\nprint((~a+b~).shape)','(2, 3)','(2, 1)|(1, 3)','The complementary singleton dimensions expand to a 2-by-3 result.','a|b'),
 S('a=np.arange(3)\nprint(a[~:,None~].shape)','(3, 1)','(1, 3)|(3,)','None inserts a singleton column axis.','None,:|:'),
 S('a=np.zeros((2,3)); b=np.ones(2)\nprint((~a+b~).shape)','ValueError: incompatible broadcast shapes','(2, 3)|(2, 2)','The trailing dimensions three and two cannot broadcast.','a+b[:,None]|a','Why does this operation fail?')),
 L('views','Views, copies, and advanced indexing','Basic slicing normally creates a view; integer-array and boolean indexing produce copies on reads. Assignment through an index expression still updates the destination. copy makes independence explicit. np.shares_memory checks actual overlap.',
 S('a=np.array([${n},0]); b=~a[:1]~; b[0]=1\nprint(int(a[0]))','1','${n}|0','The basic slice shares the original storage.','a[:1].copy()|a[[0]]'),
 S('a=np.array([${n},0]); b=~a.copy()~; b[0]=1\nprint(int(a[0]))','${n}','1|0','copy allocates independent data.','a|a[:]'),
 S('a=np.array([${n},0]); b=~a[[0]]~; b[0]=1\nprint(int(a[0]))','${n}','1|0','Advanced integer indexing returns copied data for this read.','a[:1]|a'),
 S('a=np.arange(4); b=a[1:]\nprint(~np.shares_memory(a,b)~)','True','False|None','The slices overlap the same backing allocation.','np.array_equal(a,b)|a is b')),
 L('masks','Filtering and conditional selection','Boolean indexing selects elements whose corresponding mask is true. np.where chooses between values elementwise; its arguments are evaluated before selection, so it does not automatically prevent invalid arithmetic. Masked assignment changes the original array.',
 S('a=np.array([${n},0,${m}])\nprint(a[~a>0~].tolist())','[${n}, ${m}]','[0]|[${n}, 0, ${m}]','The mask selects only positive entries.','a==0|a>=0'),
 S('a=np.array([${n},0])\nprint(np.where(a>0,~a~, -1).tolist())','[${n}, -1]','[-1, -1]|[${n}, 0]','where uses array values at true positions and the fallback elsewhere.','0|-1'),
 S('a=np.array([${n},0]); a[~a==0~]=${m}\nprint(a.tolist())','[${n}, ${m}]','[${m}, 0]|[${n}, 0]','Assignment through the mask updates matching positions in a.','a>0|a<0'),
 S('a=np.array([-1,${n},100])\nprint(np.clip(a,0,~${n}~).tolist())','[0, ${n}, ${n}]','[-1, ${n}, 100]|[0, 0, 0]','clip bounds each value between zero and the chosen upper limit.','0|100')),
 L('shape','Reshaping, transposing, and joining','reshape preserves element count, while transpose reorders axes. A reshape may copy when required by layout; do not universally assume it is a view. stack adds a new axis and concatenate joins along an existing one.',
 S('a=np.arange(6)\nprint(a.reshape(~2,3~).shape)','(2, 3)','(3, 2)|(6,)','The requested shape contains the same six elements.','3,2|6'),
 S('a=np.zeros((2,3,4))\nprint(a.transpose(~2,0,1~).shape)','(4, 2, 3)','(3, 2, 4)|(2, 3, 4)','The permutation lists the old axis for each new position.','1,0,2|0,1,2'),
 S('a=np.array([${n},${m}])\nprint(np.~stack~([a,a]).shape)','(2, 2)','(4,)|(2,)','stack introduces a new leading axis by default.','concatenate|array_equal'),
 S('a=np.array([${n},${m}])\nprint(np.~concatenate~([a,a]).shape)','(4,)','(2, 2)|(2,)','concatenate joins the two vectors along their existing axis.','stack|array_equal')),
 L('dtypes','Dtypes, missing values, and numerical checks','Dtypes constrain representation and arithmetic. astype converts values and may copy. NaN is not equal to itself; isnan detects it. allclose supports approximate comparisons, whereas exact equality is appropriate for discrete contracts.',
 S('a=np.array([${n}],dtype=np.int64)\nprint(a.astype(~np.float64~).dtype.name)','float64','int64|bool','astype explicitly converts the stored element type.','np.int64|bool'),
 S('a=np.array([np.nan,${n}])\nprint(~np.isnan(a)~.tolist())','[True, False]','[False, False]|[True, True]','isnan detects the missing floating value directly.','(a==np.nan)|(a>0)'),
 S('a=np.array([np.nan,${n}])\nprint(float(~np.nanmean(a)~))','${n}.0','nan|0.0','nanmean ignores NaN entries when computing a mean.','np.mean(a)|np.sum(a)'),
 S('print(~np.allclose~([0.1+0.2],[0.3]))','True','False|ValueError','allclose allows a small floating-point tolerance.','np.array_equal|np.shares_memory')),
 L('random','Generators and reproducible sampling','default_rng creates a Generator whose state advances with each draw. Equal seeds and matching draw sequences reproduce results within the chosen generator setup. Test ranges and shapes instead of memorizing random values. Separate generators avoid accidental global-state coupling.',
 S('rng=np.random.default_rng(7)\na=rng.integers(0,${n},size=~(2,3)~)\nprint(a.shape)','(2, 3)','(3, 2)|(6,)','size specifies the output shape independently of the sampled range.','(3,2)|6'),
 S('a=np.random.default_rng(7).integers(0,100,10)\nb=np.random.default_rng(~7~).integers(0,100,10)\nprint(np.array_equal(a,b))','True','False|ValueError','Separate generators with the same seed and calls produce equal samples.','8|9'),
 S('a=np.random.default_rng(7).integers(0,${n},100)\nprint(bool(np.all(a~<${n}~)))','True','False|ValueError','The upper bound is excluded by default.','<0|<1'),
 S('a=np.random.default_rng(7).random((2,3))\nprint(a.~dtype.name~)','float64','int64|bool','Generator.random produces float64 by default.','shape|size')),
 L('workflows','Reading numerical workflows and persistence','Read each pipeline as a sequence of shape, dtype, and ownership contracts. @ performs matrix multiplication while * is elementwise. Save/load preserves array data; avoid allowing pickle for untrusted object arrays. Assertions should check shapes and intended tolerances.',
 S('a=np.ones((2,3)); b=np.ones((3,4))\nprint((a~@~b).shape)','(2, 4)','(2, 3)|ValueError','The shared inner dimension is contracted by matrix multiplication.','*|+'),
 S('a=np.array([[${n},0],[${m},0]],dtype=float)\nb=a-a.mean(axis=~0~,keepdims=True)\nprint(b.shape)','(2, 2)','(2,)|(1, 2)','Keeping a row of column means makes the centering broadcast explicit.','1|None'),
 S('# Assume a writable temporary directory.\na=np.array([${n},${m}]); np.save("values.npy",a)\nb=np.load("values.npy",allow_pickle=~False~)\nprint(np.array_equal(a,b))','True','False|ValueError','Numeric arrays round-trip without permitting pickled objects.','None|"False"'),
 S('a=np.zeros((2,3))\nassert a.shape==~(2,3)~\nprint("ready")','ready','AssertionError|ValueError','The assertion verifies the expected two-axis shape.','(3,2)|(6,)')),
 ]
 result[5]['scenarios'][3]['completion']=S('a=np.zeros((2,3)); b=np.ones(2)\nprint((a+~b[:,None]~).shape)','(2, 3)','ValueError|(2, 2)','Insert a singleton column axis so the row offsets broadcast across columns.','b|b[None,:]')
 return result
