from build import S,lesson as L,emit,source
from common import basics

def c():
 return basics('c')+[
 L('strings','Characters and C strings','A char stores one character. A C string is a character array terminated by a zero byte. strlen excludes that terminator; sizeof an array includes all its storage.',
 S('char s[]="${word}";\nprintf("%zu", ~strlen(s)~);','${length}','${length1}|0','strlen counts bytes before the zero terminator.','sizeof(s)|0UL'),
 S('char s[]="${word}";\nprintf("%c", s[~0~]);','${first}','${word}|0','Array index zero selects the first character.','1|2'),
 S('char s[]="${word}";\nprintf("%zu", ~sizeof(s)~);','${length1}','${length}|0','The array has one extra byte for its terminating zero.','strlen(s)|0UL'),
 S('char s[]="${word}";\ns[0]=~\'X\'~;\nprintf("%s", s);','X${tail}','${word}|X','A writable array permits replacing its first character.','\'Y\'|\'\\0\'')),
 L('conditions','Conditions and boolean operators','Zero is false; nonzero is true. Comparisons yield int zero or one. && and || short-circuit, which can protect a pointer dereference.',
 S('printf("%d", ${n} ~==~ ${n});','1','0|${n}','Equality of the identical integers yields one.','!=|<'),
 S('int x=0;\nif (~${n}~) x=1;\nprintf("%d", x);','1','0|${n}','A nonzero condition enters the branch.','0|!1'),
 S('int *p=NULL;\nif (p ~&&~ *p > 0) puts("yes"); else puts("no");','no','yes|Undefined behavior','&& skips the dereference when p is null.','&|||'),
 S('printf("%d", ~!~0);','1','0|-1','Logical negation of zero yields one.','-|+')),
 L('loops','Loop bounds and control flow','for separates initialization, test, and update. < gives an exclusive upper bound. continue skips the body remainder; break exits the loop.',
 S('int x=0; for(int i=0;i~<~${n};i++) x++; printf("%d",x);','${n}','${next}|0','Starting at zero with an exclusive limit gives ${n} iterations.','<=|>'),
 S('int x=0; for(int i=0;i<3;i++) { if(i==1) ~continue~; x++; } printf("%d",x);','2','1|3','continue skips the middle increment.','break|return'),
 S('int x=0; while(1) { x++; ~break~; } printf("%d",x);','1','0|Never terminates','break exits after one increment.','continue|return'),
 S('int x=0; ~do~ { x++; } while(0); printf("%d",x);','1','0|Never terminates','A do loop runs its body before testing its condition.','if|for')),
 L('functions','Functions and value parameters','Function declarations specify return and parameter types. C passes arguments by value; use a pointer when a function should update caller storage.',
 S('int bump(int x) { return ~x+1~; }\n/* in main */ printf("%d",bump(${n}));','${next}','${n}|0','The function returns its computed expression.','x|0'),
 S('void change(int x) { x=${m}; }\n/* in main */ int x=${n}; ~change(x)~; printf("%d",x);','${n}','${m}|0','Changing the value parameter does not update the caller variable.','x=${m}|x=0'),
 S('void change(int *p) { *p=${m}; }\n/* in main */ int x=${n}; change(~&x~); printf("%d",x);','${m}','${n}|0','Passing the address lets the function modify x through the pointer.','x|NULL'),
 S('int stop(void) { ~return~ ${n}; return ${m}; }\n/* in main */ printf("%d",stop());','${n}','${m}|0','return exits before the later statement.','goto|break')),
 L('arrays','Arrays, sizes, and bounds','Arrays use zero-based indexes. sizeof can compute an array element count only while the expression is an actual array; a parameter declared as an array is adjusted to a pointer.',
 S('int a[]={${n},${m}}; printf("%d",a[~1~]);','${m}','${n}|0','Index one selects the second element.','0|2'),
 S('int a[]={${n},${m}}; printf("%zu",~sizeof(a)/sizeof(a[0])~);','2','1|0','Total array bytes divided by element bytes gives the count.','sizeof(a[0])/sizeof(a)|0UL'),
 S('int a[3]={${n}}; printf("%d",a[~2~]);','0','${n}|Indeterminate','Unspecified entries in this initializer are zero-initialized.','0|3'),
 S('int a[]={${n},${m}}; printf("%d",~a[2]~);','Undefined behavior','Always zero|Always ${m}','Index two is past the end of this two-element array.','a[0]|a[1]','What does the out-of-bounds access imply?')),
 L('io','Formatted I/O and return values','Use a format that matches the argument type. scanf needs a destination address and returns the number of successful assignments. fgets reads at most size minus one bytes.',
 S('int x; if(scanf("%d", ~&x~)==1) printf("%d",x);','${n}','0|The address of x','For input ${n}, scanf stores one integer at the supplied address.','x|NULL','Given input ${n}, what is printed?'),
 S('printf(~"%s"~, "${word}");','${word}','An address|0','%s formats a zero-terminated character string.','"%d"|"%p"'),
 S('char b[${n}]; ~fgets~(b,sizeof b,stdin);','At most ${prev} input bytes plus a terminator','Exactly ${n} input bytes|Unlimited bytes','On success fgets reserves one byte for a zero terminator.','gets|scanf','What bound applies to a successful read?'),
 S('FILE *f=fopen("notes.txt","w"); if(f) { fputs("${word}",f); ~fclose~(f); }','Writes and closes when open succeeds','Always reads|Leaves the handle open','fclose releases the file resource after writing.','fflush|rewind','What does this code do?')),
 L('units','Headers, linkage, and macros','Headers declare interfaces shared by translation units. File-scope static gives internal linkage. Parenthesize macro parameters and expressions; macros substitute tokens.',
 S('#define DOUBLE(x) (~(x)+(x)~)\n/* in main */ printf("%d",DOUBLE(${n}));','${double}','${n}|0','The macro adds its parenthesized argument twice.','x|0'),
 S('~static~ int size=${n};','Internal linkage within this translation unit','External linkage across the program|Automatic block storage','File-scope static restricts this name to its translation unit.','extern|const','What linkage does size have?'),
 S('#ifndef CONFIG_H\n#define CONFIG_H\nint size(void);\n~#endif~','Prevents duplicate inclusion of declarations','Executes the function|Allocates an integer array','The conditional header guard skips repeated contents.','#else|#undef','What purpose does this structure serve?'),
 S('~extern~ int shared;','Declares an object defined elsewhere','Defines a local automatic variable|Defines a constant expression','An extern declaration without an initializer refers to an external definition.','static|const','What does this declaration communicate?')),
 L('errors','Failure reporting and cleanup','C APIs often report failure with sentinel return values, not exceptions. Check allocation and file results before use. errno is meaningful only when the API documents it on failure.',
 S('FILE *f=fopen("missing.txt","r"); if(f ~==~ NULL) puts("failed");','failed','Nothing|Undefined behavior','A failed fopen returns NULL, so this comparison detects failure.','!=|>','Assuming fopen fails, what is printed?'),
 S('int *p=malloc(sizeof *p); if(p) { *p=${n}; printf("%d",*p); ~free~(p); }','${n}','0|An address','On successful allocation, the value is used and storage is released.','realloc|malloc','Assuming allocation succeeds, what is printed?'),
 S('int rc=-1; if(rc ~<~ 0) puts("failed");','failed','Nothing|0','A documented negative sentinel can be tested explicitly.','>|=='),
 S('if(fopen("missing.txt","r")==NULL) ~perror~("open");','Writes an errno-based diagnostic to stderr','Throws an exception|Retries the open','perror reports the current error description with the supplied prefix.','puts|printf','Assuming failure, what is the diagnostic operation?')),
 L('pointers','Pointers, const, and lifetime','& takes an address; * dereferences. A pointer is usable only while its target is alive. const on the pointed-to type prevents writes through that pointer.',
 S('int x=${n}; int *p=~&x~; *p=${m}; printf("%d",x);','${m}','${n}|0','p points to x, so dereferencing p updates x.','NULL|0'),
 S('int a[]={${n},${m}}; int *p=a; printf("%d",~*(p+1)~);','${m}','${n}|An address','Pointer arithmetic advances by one int element.','*p|a[0]'),
 S('int x=${n}; ~const int *~p=&x;','Cannot assign through *p','Cannot reassign p|x becomes globally immutable','The pointed-to type is const; the pointer itself is not const.','int *const |int *','Which restriction follows from this declaration?'),
 S('int *bad(void) { int x=${n}; return ~&x~; }','Returns a pointer to an expired local object','Returns owned heap storage|Returns an integer copy','The automatic local lifetime ends when the function returns.','NULL|0','Why is dereferencing the returned non-null pointer invalid?')),
 L('records','Structures, enums, and typedef','Structures group named fields. . accesses a value and -> accesses through a pointer. typedef introduces an alias; enums define named integer constants.',
 S('struct Box { int size; }; struct Box b={${n}}; printf("%d",b~.size~);','${n}','0|An address','Dot selects a field from the structure value.','->size|.other'),
 S('struct Box { int size; }; struct Box b={${n}}; struct Box *p=&b; printf("%d",p~->size~);','${n}','0|An address','Arrow selects a field through a structure pointer.','.size|->other'),
 S('enum State { OFF, ON }; printf("%d",~ON~);','1','0|2','Implicit enum values start at zero and increment.','OFF|0'),
 S('~typedef~ struct { int size; } Box; Box b={${n}}; printf("%d",b.size);','${n}','0|Compile error','typedef gives this structure type the alias Box.','static|extern')),
 L('memory','Dynamic memory and ownership','malloc gives uninitialized storage; calloc zero-initializes. free ends its lifetime. Keep the original pointer until realloc succeeds, and free exactly once.',
 S('int *p=~calloc~(1,sizeof *p); if(p) { printf("%d",*p); free(p); }','0','Indeterminate|1','calloc zero-initializes the allocated integer storage.','malloc|realloc','Assuming allocation succeeds, what is printed?'),
 S('int *p=malloc(sizeof *p); if(p) { *p=${n}; free(p); printf("%d",~*p~); }','Undefined behavior','Always ${n}|Always zero','The pointer no longer refers to a live allocated object after free.','${n}|0','Assuming allocation succeeds, what follows from the final access?'),
 S('int *tmp=~realloc~(p,new_bytes); if(tmp) p=tmp;','Preserves the old allocation if resizing fails','Always frees p on failure|Always keeps the same address','Using a temporary avoids losing p when realloc returns NULL; assume new_bytes is nonzero.','malloc|calloc','Assume p is a live allocation: why use tmp?'),
 S('int *p=NULL; ~free~(p);','No effect','Undefined behavior|Allocates memory','free accepts a null pointer and does nothing.','malloc|realloc','What happens?')),
 L('callbacks','Function pointers and low-level qualifiers','Function pointers describe callable signatures. unsigned arithmetic wraps modulo the type range. volatile does not provide thread synchronization.',
 S('int bump(int x) { return x+1; }\n/* in main */ int (*f)(int)=~bump~; printf("%d",f(${n}));','${next}','${n}|0','f stores a pointer to a function with the matching signature.','NULL|0'),
 S('unsigned int x=0; printf("%d", (x-1) ~==~ UINT_MAX);','1','0|Undefined behavior','Unsigned subtraction wraps to the maximum representable unsigned value.','!=|<'),
 S('~volatile~ int flag;','Accesses must follow volatile access rules','Makes increments atomic|Creates a mutex','volatile preserves observable accesses; it is not an atomic synchronization mechanism.','_Atomic|static','What does the qualifier promise?'),
 S('int a=${n}; int b=${m}; int *p=&a; p=~&b~; printf("%d",*p);','${m}','${n}|0','Reassigning a pointer changes its target, not either integer value.','&a|NULL'))]

def cpp():
 return basics('cpp')+[
 L('strings','Strings and value types','std::string owns text and supports value copying. size counts stored characters for these ASCII examples; operator+ concatenates.',
 S('std::string s="${word}"; std::cout << s.~size()~;','${length}','0|${n}','size reports the number of characters in this string.','empty()|front()'),
 S('std::string s="${word}"; std::cout << s ~+~ s;','${joined}','${word}|Compile error','+ concatenates two strings.','==|<'),
 S('std::string s="${word}"; std::cout << s[~0~];','${first}','${word}|0','Index zero reads the first character.','1|2'),
 S('std::string a="${word}"; auto b=a; b[0]=~\'X\'~; std::cout << a;','${word}','X${tail}|X','Copying std::string creates independent value storage.','\'Y\'|\'Z\'')),
 L('conditions','Comparisons and scoped branches','bool represents true or false. Comparisons produce bool. && short-circuits; if can introduce a local initializer whose scope spans both branches.',
 S('std::cout << (${n} ~==~ ${n});','1','0|${n}','Without boolalpha, true is printed as one.','!=|<'),
 S('int *p=nullptr; std::cout << (p ~&&~ *p>0);','0','1|Undefined behavior','Short-circuit evaluation avoids dereferencing the null pointer.','&|||'),
 S('if(int x=${n}; x>0) std::cout << ~x~;','${n}','0|Compile error','The initializer variable is available in the condition and branch.','0|nullptr'),
 S('std::cout << (~false~ ? ${n} : ${m});','${m}','${n}|0','A false condition selects the expression after the colon.','true|${n}')),
 L('loops','Loops and range iteration','Range-for reads elements directly. auto copies each value; auto& binds to the element so modifications persist. continue skips an iteration.',
 S('int x=0; for(int i=0;i~<~${n};++i) ++x; std::cout<<x;','${n}','${next}|0','The exclusive upper bound gives ${n} iterations.','<=|>'),
 S('int a[]={${n},${m}}; int x=0; for(auto v ~:~ a) x+=v; std::cout<<x;','${add}','${mul}|0','Range-for visits both values.',';|,'),
 S('int a[]={${n}}; for(~auto&~ v:a) ++v; std::cout<<a[0];','${next}','${n}|0','The reference binds directly to the array element.','auto|const auto&'),
 S('int x=0; for(int i=0;i<3;++i) {if(i==1) ~continue~; ++x;} std::cout<<x;','2','1|3','continue skips only the middle increment.','break|return')),
 L('functions','Parameters, overloads, and defaults','Overloads select a matching signature. Values copy; references alias. Default arguments fill omitted trailing arguments.',
 S('int bump(int x) {return ~x+1~;}\n// in main\nstd::cout<<bump(${n});','${next}','${n}|0','The return expression computes one more than the argument.','x|0'),
 S('void bump(~int&~ x) {++x;}\n// in main\nint x=${n}; bump(x); std::cout<<x;','${next}','${n}|0','A reference parameter updates the caller object.','int|const int&'),
 S('int value(int x=${n}) {return x;}\n// in main\nstd::cout<<~value()~;','${n}','0|Compile error','The omitted argument uses the default.','value(0)|value(nullptr)'),
 S('int f(int) {return 1;} int f(double) {return 2;}\n// in main\nstd::cout<<f(~${n}.0~);','2','1|Compile error','A double literal selects the double overload.','${n}|true')),
 L('containers','Standard containers and checked access','std::vector owns a resizable sequence; std::array has a fixed size. at checks bounds. These lessons concern library type usage, not implementing data structures.',
 S('std::vector<int> a={${n},${m}}; std::cout<<a.at(~1~);','${m}','${n}|0','at(1) selects the second element with bounds checking.','0|2'),
 S('std::vector<int> a={${n}}; a.~push_back~(${m}); std::cout<<a.size();','2','1|0','push_back appends one element.','resize|assign'),
 S('std::array<int,3> a{${n}}; std::cout<<a[~2~];','0','${n}|Indeterminate','Remaining aggregate-initialized integer elements are zero.','0|3'),
 S('std::vector<int> a={${n}}; std::cout<<a.~at(1)~;','Throws std::out_of_range','Always zero|Undefined behavior','at checks that the requested index is within the vector.','at(0)|size()','What happens?')),
 L('io','Streams and input state','Streams use << for output and >> for formatted input. Input operations set state on failure. getline reads a line; stream objects manage their file resources.',
 S('int x=0; std::cin ~>>~ x; std::cout<<x;','${n}','0|An address','Formatted extraction parses an integer into x.','<<|==','Given valid input ${n}, what is printed?'),
 S('std::string s; std::~getline~(std::cin,s); std::cout<<s;','${word}','Empty string|An address','getline reads text up to the newline into s.','move|size','Given the line ${word}, what is printed?'),
 S('std::istringstream in("bad"); int x=0; in>>x; std::cout<<in.~fail()~;','1','0|Compile error','Invalid integer extraction sets the failure state.','good()|eof()'),
 S('{ std::ofstream f("notes.txt"); f ~<<~ "${word}"; }','Writes text; destruction closes the file','Requires explicit delete|Only reads the file','The stream owns its resource and closes it at scope exit; assume opening succeeds.','>>|==','What resource behavior applies?')),
 L('names','Namespaces and type deduction','Namespaces qualify names. auto deduces a type from an initializer; const prevents mutation through that binding. using can introduce type aliases.',
 S('namespace cfg {constexpr int size=${n};}\n// in main\nstd::cout<<cfg~::~size;','${n}','0|Compile error',':: resolves a namespace member.','.|->'),
 S('~using~ Count=int; Count x=${n}; std::cout<<x;','${n}','0|Compile error','using introduces the alias Count for int.','typedef|namespace'),
 S('~auto~ x=${n}; std::cout<<x+1;','${next}','${n}|0','auto deduces int from the integer initializer.','void|std::string'),
 S('~const~ int x=${n}; x=${m};','Compile error','Updates x|Undefined behavior','A const-qualified integer cannot be reassigned.','static|unsigned','What happens at assignment?')),
 L('exceptions','Exceptions and unwinding','throw raises an exception; catch handles matching types. Stack unwinding destroys automatic objects, which supports reliable cleanup.',
 S('try {throw std::runtime_error("${word}");} ~catch~ (const std::exception& e) {std::cout<<e.what();}','${word}','Exception escapes|0','The base exception reference handles this derived exception.','if|while'),
 S('~throw~ std::invalid_argument("${word}");','Raises an exception','Returns a value|Prints the message','throw transfers control to a matching handler.','return|sizeof','What happens?'),
 S('try {std::vector<int> a; a.at(0);} catch(const ~std::out_of_range~&) {std::cout<<${n};}','${n}','0|Undefined behavior','The checked access throws out_of_range.','std::bad_alloc|std::bad_cast'),
 S('struct Guard {~__TILDE__Guard()~{std::cout<<"closed";} };\n// in main\n{ Guard g; }','closed','Nothing|Compile error','The destructor runs when the automatic object leaves scope.','Guard()|close()')),
 L('classes','Classes and encapsulation','Constructors initialize fields. private restricts access. const member functions promise not to mutate ordinary instance fields through this.',
 S('class Box {int x; public: Box(int n):~x(n)~{} int get() const{return x;} };\n// in main\nstd::cout<<Box(${n}).get();','${n}','0|Indeterminate','The member initializer initializes x before the constructor body.','x(0)|x()'),
 S('struct Box {int x; int get() ~const~ {return x;}};\n// in main\nconst Box b{${n}}; std::cout<<b.get();','${n}','Compile error|0','A const member function can be called on a const object.','volatile|mutable'),
 S('class Box {~public~: int x=${n};};\n// in main\nstd::cout<<Box{}.x;','${n}','Compile error|0','public makes this field accessible from outside the class.','private|protected'),
 S('struct Box {int x;}; Box a{${n}}; auto b=a; b.x=~${m}~; std::cout<<a.x;','${n}','${m}|0','Copying this value object copies its integer field.','0|${n}')),
 L('ownership','RAII and smart pointers','RAII ties resource lifetime to object lifetime. unique_ptr owns exclusively; moving transfers ownership. shared_ptr shares ownership and counts owners.',
 S('auto p=std::~make_unique<int>~(${n}); std::cout<<*p;','${n}','0|An address','make_unique allocates an integer with exclusive automatic ownership.','make_shared<int>|make_unique<double>'),
 S('auto p=std::make_unique<int>(${n}); auto q=~std::move(p)~; std::cout<<(p==nullptr);','1','0|Compile error','Moving unique_ptr transfers ownership and leaves p empty.','p|nullptr'),
 S('auto p=std::make_shared<int>(${n}); auto q=p; std::cout<<p.~use_count()~;','2','1|0','Two shared_ptr objects now share ownership.','get()|unique()'),
 S('auto p=std::make_unique<int>(${n}); p.~reset()~; std::cout<<(p==nullptr);','1','0|Compile error','reset destroys the owned object and empties the pointer.','get()|operator*()')),
 L('templates','Templates and callable objects','Templates are instantiated for argument types. Lambdas form callable objects with explicit captures. Value captures preserve a copy; reference captures follow the variable.',
 S('template<class T> T twice(T x){return ~x+x~;}\n// in main\nstd::cout<<twice(${n});','${double}','${n}|0','The template is instantiated for int and adds two copies.','x|T{}'),
 S('int x=${n}; auto f=[~x~]{return x;}; x=${m}; std::cout<<f();','${n}','${m}|0','Value capture retains the integer from lambda creation.','&x|&'),
 S('int x=${n}; auto f=[~&x~]{return x;}; x=${m}; std::cout<<f();','${m}','${n}|0','Reference capture observes the later reassignment.','x|='),
 S('auto f=[](auto x){return ~x+1~;}; std::cout<<f(${n});','${next}','${n}|0','A generic lambda deduces its parameter type for the call.','x|0')),
 L('polymorphism','Virtual dispatch and optional values','Virtual methods dispatch through base references or pointers. override checks an intended override. optional represents a value that may be absent.',
 S('struct Base {virtual int get() const{return 1;}}; struct Child:Base {int get() const ~override~ {return ${n};}};\n// in main\nChild c; Base& b=c; std::cout<<b.get();','${n}','1|0','Virtual dispatch invokes the overriding Child method.','constexpr|static'),
 S('std::optional<int> x; std::cout<<x.~value_or~(${n});','${n}','0|Throws','value_or supplies a fallback for an empty optional.','value|emplace'),
 S('std::optional<int> x=${n}; std::cout<<x.~value_or~(${m});','${n}','${m}|0','An engaged optional returns its own value.','emplace|reset'),
 S('struct Base {~virtual~ __TILDE__Base()=default;};','Supports destruction through a base pointer','Makes every member virtual|Prevents inheritance','A virtual destructor enables correct polymorphic destruction.','static|const','What does this declaration enable?'))]

def rust():
 return basics('rust')+[
 L('text','Strings, slices, and UTF-8','String owns growable UTF-8 text; &str borrows a string slice. len counts bytes, not Unicode characters. Examples here use ASCII to make lengths explicit.',
 S('let s="${word}"; println!("{}",s.~len()~);','${length}','0|${n}','len reports the byte length of this ASCII slice.','is_empty()|to_uppercase()'),
 S('let mut s=String::from("${word}"); s.~push_str~("${word}"); println!("{}",s);','${joined}','${word}|Compile error','push_str appends a borrowed string slice to the owned string.','push|clear'),
 S('let s="${word}"; println!("{}",s.~to_uppercase()~);','${upper}','${word}|0','to_uppercase produces uppercase text.','to_lowercase()|len()'),
 S('let s=String::from("${word}"); let view: &str=~&s~; println!("{}",view);','${word}','An address|Compile error','Borrowing String can coerce to a string slice without transferring ownership.','s|&0')),
 L('branches','Boolean conditions and expressions','Rust conditions must be bool. if and match can produce values. Both branches of an if expression must have compatible types.',
 S('let x=if ~true~ {${n}} else {${m}}; println!("{}",x);','${n}','${m}|Compile error','The true branch produces the expression value.','false|0'),
 S('println!("{}",${n} ~==~ ${n});','true','false|1','Equality produces a boolean, printed as true or false.','!=|<'),
 S('let x=Some(${n}); if let ~Some(v)~=x {println!("{}",v);} ','${n}','Nothing|Compile error','if let extracts the inner value when the pattern matches.','None|Some(_)'),
 S('let x=match ~false~ {true=>${n}, false=>${m}}; println!("{}",x);','${m}','${n}|Compile error','The matching false arm determines the value.','true|0')),
 L('loops','Ranges and loop expressions','a..b excludes b; a..=b includes it. loop can yield a value through break. for consumes an iterator rather than a C-style condition/update clause.',
 S('let mut x=0; for _ in 0~..~${n} {x+=1;} println!("{}",x);','${n}','${next}|0','The half-open range visits zero through ${prev}.','..=|+='),
 S('let mut x=0; for _ in 1~..=~${n} {x+=1;} println!("{}",x);','${n}','${prev}|0','The inclusive range contains ${n} values.','..|+='),
 S('let x=loop {~break~ ${n};}; println!("{}",x);','${n}','0|Never terminates','break supplies the value of the loop expression.','continue|return'),
 S('let mut x=0; for i in 0..3 {if i==1 {~continue~;} x+=1;} println!("{}",x);','2','1|3','continue skips only the middle increment.','break|return')),
 L('functions','Functions and expression returns','Parameter types are explicit. The final expression without a semicolon is returned; a semicolon discards its value and leaves unit. return can exit early.',
 S('fn bump(x:i32)->i32 {~x+1~}\n// in main\nprintln!("{}",bump(${n}));','${next}','${n}|Compile error','The trailing expression supplies the i32 return value.','x+1;|()'),
 S('fn stop()->i32 {~return~ ${n};}\n// in main\nprintln!("{}",stop());','${n}','0|Compile error','return explicitly exits with an i32 value.','break|let'),
 S('fn change(mut x:i32){x=${m};}\n// in main\nlet x=${n}; ~change(x)~; println!("{}",x);','${n}','${m}|Compile error','The i32 argument is copied; modifying the local copy leaves x unchanged.','x=${m}|drop(x)'),
 S('fn size()->~usize~ {"${word}".len()}\n// in main\nprintln!("{}",size());','${length}','0|Compile error','String length returns usize, the pointer-sized unsigned type.','i32|bool')),
 L('collections','Tuples, arrays, and vectors','Tuples may mix types; arrays have a fixed length; Vec owns a growable sequence. get returns Option instead of panicking on an absent index.',
 S('let t=(${n},"${word}"); println!("{}",t.~1~);','${word}','${n}|Compile error','Tuple field one contains the text.','0|2'),
 S('let a=[${n};3]; println!("{}",a[~2~]);','${n}','0|3','Array repetition initializes all three elements to ${n}.','3|4'),
 S('let mut a=vec![${n}]; a.~push~(${m}); println!("{}",a.len());','2','1|0','push appends one element to the vector.','pop|clear'),
 S('let a=vec![${n}]; println!("{}",a.~get(1)~.is_none());','true','false|Panics','get returns None for an out-of-bounds index.','get(0)|first()')),
 L('io','Parsing and basic I/O','Text parsing returns Result. read_line appends text and retains a newline. trim removes surrounding whitespace before parsing. Handle errors explicitly.',
 S('let x: i32="${n}".~parse()~.unwrap(); println!("{}",x+${m});','${add}','${n}${m}|Compile error','parse uses the expected i32 type to convert valid digit text.','len()|to_string()'),
 S('let s=" ${word}\n"; println!("{}",s.~trim()~);','${word}',' ${word}\n|Empty string','trim removes leading and trailing whitespace.','to_uppercase()|len()'),
 S('let x="bad".parse::<i32>(); println!("{}",x.~is_err()~);','true','false|Panics','Parsing invalid numeric text returns Err without panicking.','is_ok()|unwrap()'),
 S('let x="bad".parse::<i32>().~unwrap_or~(${n}); println!("{}",x);','${n}','0|Panics','unwrap_or supplies a value when the Result is Err.','expect|unwrap')),
 L('modules','Modules, visibility, and imports','mod introduces a module. Items are private by default; pub makes an item accessible from the parent. use brings paths into local scope.',
 S('mod cfg {~pub~ const SIZE:i32=${n};}\n// in main\nprintln!("{}",cfg::SIZE);','${n}','Compile error|0','pub makes SIZE accessible from the parent module.','static|mut'),
 S('mod cfg {pub const SIZE:i32=${n};}\n~use~ cfg::SIZE;\n// in main\nprintln!("{}",SIZE);','${n}','Compile error|0','use introduces the qualified item under its short name.','mod|impl'),
 S('mod cfg {pub const SIZE:i32=${n};}\n// in main\nprintln!("{}",cfg~::~SIZE);','${n}','Compile error|0',':: separates path components.','.|->'),
 S('const SIZE: i32=~${n}~;\n// in main\nprintln!("{}",SIZE);','${n}','0|Compile error','A const item is initialized with a constant expression.','String::new()|true')),
 L('results','Option, Result, and propagation','Option models absence, Result models success or error. match handles variants explicitly. ? returns early with the error from a compatible Result-returning function.',
 S('let x:Option<i32>=None; println!("{}",x.~unwrap_or~(${n}));','${n}','0|Panics','unwrap_or supplies a fallback for None.','expect|unwrap'),
 S('let x:Result<i32,&str>=Ok(${n}); println!("{}",x.~unwrap()~);','${n}','0|Panics','unwrap extracts the known Ok value.','is_err()|is_ok()'),
 S('fn parse(s:&str)->Result<i32,std::num::ParseIntError>{let n=s.parse::<i32>()~?~; Ok(n+1)}\n// in main\nprintln!("{}",parse("${n}").unwrap());','${next}','${n}|Compile error','? extracts Ok or returns an Err early.','!|;'),
 S('let x:Option<i32>=Some(${n}); let v=match x {~Some(n)~=>n,None=>0}; println!("{}",v);','${n}','0|Compile error','The Some pattern binds the contained integer.','Some(_)|Ok(n)')),
 L('ownership','Moves, Copy, and Drop','An owned String moves on assignment unless cloned. Copy types such as i32 are duplicated implicitly. Drop releases owned resources when their owner leaves scope.',
 S('let a=String::from("${word}"); let b=~a~; println!("{}",a);','Compile error: a was moved','Prints ${word}|Prints an address','Moving the String transfers ownership and prevents later use of a.','a.clone()|&a','What happens at the final use of a?'),
 S('let a=String::from("${word}"); let b=~a.clone()~; println!("{} {}",a,b);','${word} ${word}','Compile error|Empty string','clone makes a separate owned String.','a|drop(a)'),
 S('let a=${n}; let b=~a~; println!("{}",a+b);','${double}','${n}|Compile error','i32 implements Copy, so a remains usable after assignment.','0|1'),
 S('let a=String::from("${word}"); ~drop(a)~; println!("{}",a);','Compile error: a was moved','Prints ${word}|Runtime exception','drop takes ownership, leaving no usable binding a.','drop(&a)|println!("{}",a)','What happens at the final line?')),
 L('borrowing','References and lifetimes','Shared references permit reading; exclusive mutable references permit updates. References cannot outlive their referents. Elision supplies common lifetime relationships automatically.',
 S('let mut x=${n}; let p=~&mut x~; *p+=1; println!("{}",x);','${next}','${n}|Compile error','A mutable reference permits updating x through dereference.','&x|x'),
 S('fn size(s:~&str~)->usize{s.len()}\n// in main\nlet s=String::from("${word}"); println!("{}",size(&s));','${length}','0|Compile error','A borrowed string slice permits reading without taking ownership.','String|i32'),
 S('fn bad()->&\'static str {let s=String::from("${word}"); ~&s~}','Compile error: reference outlives local storage','Returns permanent text|Allocates a static String','The local String is destroyed on return, so its borrow cannot be static.','"${word}"|""','Why is this return rejected?'),
 S('let x=${n}; let p=~&x~; println!("{}",*p);','${n}','An address|Compile error','The shared reference can be dereferenced for reading.','x|&true')),
 L('traits','Structs, methods, and traits','Structs group fields; impl defines associated behavior. Traits describe shared contracts. &self borrows the receiver; derive can generate standard trait implementations.',
 S('struct Boxed {size:i32}\n// in main\nlet b=Boxed{size:${n}}; println!("{}",b.~size~);','${n}','0|Compile error','Dot syntax reads a named field.','len()|value'),
 S('struct Boxed {size:i32}\nimpl Boxed {fn get(~&self~)->i32{self.size}}\n// in main\nprintln!("{}",Boxed{size:${n}}.get());','${n}','0|Compile error','&self borrows the instance for the method.','self: i32|&mut self'),
 S('trait SizedValue {fn value(&self)->i32;}\nstruct Boxed;\n~impl~ SizedValue for Boxed {fn value(&self)->i32{${n}}}\n// in main\nprintln!("{}",Boxed.value());','${n}','0|Compile error','impl supplies the trait behavior for this type.','trait|mod'),
 S('#[derive(~Debug~)]\nstruct Boxed {size:i32}\n// in main\nprintln!("{:?}",Boxed{size:${n}});','Boxed { size: ${n} }','${n}|Compile error','Debug derives the formatter used by {:?}.','Copy|Clone')),
 L('iterators','Closures and lazy iterators','Closures capture context as needed. Iterator adapters are lazy until consumed. iter borrows elements; into_iter can consume the collection. collect builds a chosen result type.',
 S('let f=|x| ~x+1~; println!("{}",f(${n}));','${next}','${n}|Compile error','The closure returns one more than its argument.','x|0'),
 S('let v=vec![${n},${m}]; let x:i32=v.iter().~sum()~; println!("{}",x);','${add}','${mul}|2','sum consumes the iterator and combines its numeric values.','count()|len()'),
 S('let v:Vec<_>=(1..3).~map~(|x|x*2).collect(); println!("{:?}",v);','[2, 4]','[1, 2]|[]','map transforms each item; collect drives the lazy iterator.','filter|inspect'),
 S('let s=String::from("${word}"); let f=~move~ || s; let result=f(); println!("{}",result);','${word}','Compile error|An address','move captures ownership; this closure returns that owned String when called.','mut|pub'))]

def build():
 from build import DERIVED
 DERIVED.update(length1='len(word)+1',tail='word[1:]')
 emit('c','C','C17; standard headers such as stdio.h, stdlib.h, string.h, and limits.h are assumed where used', [source('cs50c','CS50x C lectures','https://cs50.harvard.edu/x/weeks/1/'),source('gnu-c','GNU C language manual (portable C subset here)','https://www.gnu.org/software/c-intro-and-ref/manual/html_node/')],c())
 emit('cpp','C++','C++20; relevant standard headers and a main function are assumed', [source('learncpp','Learn C++','https://www.learncpp.com/')],cpp())
 from rust_course import build as build_rust
 build_rust()
