"""Kotlin idioms on the JVM, with standard-library coroutine boundaries."""
from build import S, lesson as L


def lessons():
 return [
 L('toolchain','Kotlin/JVM and program structure','Kotlin/JVM compiles to JVM bytecode and interoperates with Java. A top-level main is an entry point; ordinary top-level functions need no wrapper class in Kotlin source. Package declarations qualify names. The CLI compiler and Gradle are build tools, separate from language syntax.',
 S('fun ~main~() { println("${word}") }','${word}','No output|Compile error','A conventional top-level main runs when the program is launched.','start|run'),
 S('$ kotlinc Main.kt ~-include-runtime~ -d app.jar','Packages the Kotlin runtime into the output JAR','Runs Android Studio|Creates native machine code','This flag includes runtime classes for running the JAR with Java.','-version|-help','What does the option request?'),
 S('$ java ~-jar~ app.jar','Runs the executable JAR on the JVM','Compiles Kotlin source|Starts a Kotlin REPL','Java launches the JAR using its entry-point metadata.','-version|-help','What does this command do?'),
 S('~package~ sample','Declares a package namespace','Installs sample|Creates an instance','The package declaration qualifies declarations in this source file.','import|class','What does the declaration establish?')),
 L('bindings','Val, var, and numeric types','val prevents rebinding and var permits it; neither alone controls mutation of the referenced object. Types are inferred statically. Numeric conversions are explicit, and integer division returns an integer. Kotlin does not implicitly widen Int to Long for assignments.',
 S('var n=${n}; n++; println(~n~)','${next}','${n}|0','var allows updating the inferred Int binding.','n-1|0'),
 S('val n=${n}; val wide:Long=n.~toLong()~; println(wide)','${n}','Compile error|0','toLong performs the explicit numeric conversion.','toString()|toDouble()'),
 S('println(${n} ~/~ ${m})','${div}','${mul}|${add}','Dividing two Int values drops the fractional part.','*|+'),
 S('val a=mutableListOf(${n}); a.~add~(${m}); println(a.size)','2','1|Compile error','val stabilizes the reference, but the mutable list can still change.','remove|contains')),
 L('strings','String templates and equality','String templates use $name or ${expression}; generated examples avoid confusing these with template parameters. == means structural equality and === means reference identity. Strings are immutable; length counts UTF-16 code units on the JVM.',
 S('val name="${word}"; println(~"Hello $name"~)','Hello ${word}','Hello $name|Compile error','A Kotlin string template inserts the local variable value.','"Hello name"|name'),
 S('println("${word}".~uppercase()~)','${upper}','${word}|Compile error','uppercase returns a new string.','lowercase()|trim()'),
 S('println("${word}".~length~)','${length}','0|Compile error','length is a property, not a method.','length()|size'),
 S('println("${word}" ~==~ "${word}")','true','false|Compile error','Structural equality compares string content.','!=|!==')),
 L('expressions','If and when as expressions','if and when can return values. Branch result types must fit the receiving type. A when expression needs exhaustive handling. Conditions require Boolean, and short-circuit operators avoid unnecessary evaluation.',
 S('val label=if(${n} ~>~ 0) "yes" else "no"; println(label)','yes','no|Compile error','if selects a value for label.','<|=='),
 S('val n=when("ready"){"ready" ~->~ ${n};else -> 0}; println(n)','${n}','0|Compile error','An arrow separates a when condition from its value.','=>|:'),
 S('val n=${n}; println(when {n>0 -> "positive"; ~else~ -> "other"})','positive','other|Compile error','A condition-based when evaluates branches in order.','default|otherwise'),
 S('var n=0; val ok=false ~&&~ (++n>0); println(n)','0','1|Compile error','The increment is skipped when the left operand is false.','|||and')),
 L('loops','Ranges and iteration','.. includes its endpoint; until excludes it. for works with iterable values and ranges. withIndex provides index/value pairs. break and continue control loops; Kotlin ranges are not Python-style slicing syntax.',
 S('println((1 ~until~ ${n}).count())','${prev}','${n}|${next}','until omits the end value.','..|downTo'),
 S('println((1~..~${n}).count())','${n}','${prev}|0','A closed range includes both endpoints.',' until | downTo '),
 S('var n=0; repeat(${n}) {n++}; println(~n~)','${n}','0|${next}','repeat invokes its lambda the given number of times.','0|n+1'),
 S('var n=0; for(i in 0..2){if(i==1) ~continue~;n++}; println(n)','2','1|3','Only one of the three iterations skips the increment.','break|return')),
 L('functions','Defaults, named arguments, and expression bodies','Functions can have default arguments and named call-site arguments. Expression bodies infer return types. A vararg receives several values; the spread operator passes an existing array. Prefer named arguments when adjacent parameters share a type.',
 S('fun bump(n:Int)=~n+1~\nprintln(bump(${n}))','${next}','${n}|0','The expression body supplies the returned Int.','n|0'),
 S('fun label(text:String="${word}")=text\nprintln(~label()~)','${word}','Empty string|Compile error','Omitting the argument chooses the default.','label("")|label'),
 S('fun size(limit:Int,enabled:Boolean)=if(enabled) limit else 0\nprintln(size(~enabled=true,limit=${n}~))','${n}','0|Compile error','Named arguments make the parameter roles explicit and allow this order.','true,${n}|limit=0,enabled=true'),
 S('fun count(vararg xs:Int)=xs.size\nval a=intArrayOf(${n},${m}); println(count(~*a~))','2','1|Compile error','The spread operator expands the primitive array into vararg elements.','a|&a')),
 L('nulls','Nullable types and safe access','String? admits null, while String does not. ?. conditionally accesses a member, ?: provides an Elvis fallback, and !! throws if its operand is null. Null safety depends on contracts; Java platform types need particular care.',
 S('val text:String?=null; println(text~?.~length ?: 0)','0','Throws NullPointerException|Compile error','Safe access returns null without calling length; Elvis supplies zero.','.|!!.'),
 S('val n:Int?=null; println(n ~?:~ ${n})','${n}','null|Compile error','Elvis evaluates the fallback only when the left side is null.','??|||'),
 S('val text:String?="${word}"; if(text!=null) println(~text.length~)','${length}','Compile error|0','The stable local value is smart-cast to non-null in this branch.','text|0'),
 S('val text:String?=null; try {println(text~!!~.length)} catch(e:NullPointerException){println("null")}','null','0|Compile error','The non-null assertion checks at runtime and throws on null.','?|?: ""')),
 L('smartcasts','Type checks and safe casts','is checks a runtime type. Smart casts work only when the compiler can rely on a stable value. as? returns null for incompatible types, whereas as throws. Mutation and custom getters can prevent smart casts.',
 S('val x:Any="${word}"; if(x ~is String~) println(x.length)','${length}','0|Compile error','The type check refines x within the successful branch.','is Int|as String'),
 S('val x:Any=${n}; val text=x ~as? String~; println(text ?: "missing")','missing','Throws ClassCastException|Compile error','A safe cast yields null when the dynamic type is incompatible.','as String|is String'),
 S('val x:Any="${word}"; println(x ~is Int~)','false','true|Compile error','The runtime value is a String, not an Int.','is String|!is Int'),
 S('val x:Any?=null; println(x ~is String~)','false','true|Throws NullPointerException','A non-null String type test fails for null.','is String?|!is String')),
 L('collections','Read-only and mutable collection views','List exposes reading while MutableList exposes updates; read-only does not guarantee deep immutability or an unchanging backing object. getOrNull makes an out-of-range read explicit. Map absence and nullable stored values can require separate key-presence checks.',
 S('val a=mutableListOf(${n}); a.~add~(${m}); println(a.size)','2','1|Compile error','MutableList exposes add.','remove|contains'),
 S('val a=listOf(${n}); println(a.~getOrNull~(3) ?: 0)','0','Throws IndexOutOfBoundsException|Compile error','getOrNull turns a missing index into null.','get|elementAt'),
 S('val a=mutableListOf(${n}); val view:List<Int> = a; a.add(${m}); println(view.~size~)','2','1|Compile error','The read-only view still refers to the same mutable backing list.','size()|length'),
 S('val m=mapOf("${word}" to ${n}); println(m.~getValue~("${word}"))','${n}','null|Compile error','getValue retrieves a required key and would throw if it were missing.','containsKey|isEmpty')),
 L('classes','Constructors and properties','Primary constructors put state near the class declaration. val and var constructor parameters become properties. Property access can execute getters and setters. Classes are final by default; open opts into inheritance.',
 S('class Item(~val name:String~)\nprintln(Item("${word}").name)','${word}','Compile error|null','val declares a read-only property initialized by the constructor.','name:String|val name:Int'),
 S('class Counter(var n:Int){fun bump(){n++}}\nval c=Counter(${n}); c.~bump()~; println(c.n)','${next}','${n}|Compile error','A member function updates this object property.','toString()|hashCode()'),
 S('class Item(val n:Int){val double:Int ~get()=n*2~}\nprintln(Item(${n}).double)','${double}','${n}|Compile error','The custom getter computes the value when read.','get()=n|get()=0'),
 S('~open~ class Base\nclass Child:Base()','Allows Child to inherit Base','Makes Base abstract|Makes all Base methods overridable','open permits class inheritance; members have separate overridability rules.','data|sealed','What does open permit here?')),
 L('data','Data classes and shallow copies','Data classes generate equals, hashCode, toString, component functions, and copy using primary-constructor properties. copy is shallow: referenced mutable objects remain shared. Destructuring binds components in their declared order.',
 S('data class Item(val n:Int)\nprintln(Item(${n}) ~==~ Item(${n}))','true','false|Compile error','Generated equality compares primary-constructor properties.','!=|==='),
 S('data class Item(val n:Int)\nval a=Item(${n}); val b=a.~copy~(n=${m}); println(a.n)','${n}','${m}|Compile error','copy makes a new data-class instance without changing a.','equals|component1'),
 S('data class Item(val name:String,val n:Int)\nval (name,n)=~Item("${word}",${n})~; println(name)','${word}','${n}|Compile error','Destructuring invokes generated component functions in declaration order.','"${word}"|${n}'),
 S('data class Item(val xs:MutableList<Int>)\nval a=Item(mutableListOf(${n})); val b=a.copy(); b.xs.add(${m}); println(a.xs.~size~)','2','1|Compile error','The shallow copy shares the mutable list reference.','length|size()')),
 L('extensions','Extension functions and static resolution','Extensions add callable syntax without modifying a class. They are resolved using the declared receiver type, not virtual dispatch. Members take precedence over matching extensions. Nullable receivers can explicitly handle null.',
 S('fun String.~tag~()="["+this+"]"\nprintln("${word}".tag())','[${word}]','${word}|Compile error','The extension uses this as its String receiver.','Tag|label'),
 S('fun String?.label()=~this ?: "missing"~\nval x:String?=null; println(x.label())','missing','Throws NullPointerException|Compile error','An extension on a nullable receiver can handle null explicitly.','this!!|"present"'),
 S('open class Base\nclass Child:Base()\nfun Base.label()="base"\nfun Child.label()="child"\nval x:Base=Child(); println(~x.label()~)','base','child|Compile error','Extension selection uses the static receiver type Base.','(x as Child).label()|"child"'),
 S('val String.firstChar:Char ~get()=this[0]~\nprintln("${word}".firstChar)','${first}','${word}|Compile error','An extension property has accessors but no backing field.','get()=this|get()=0')),
 L('lambdas','Higher-order functions and trailing lambdas','Function types express inputs and result. A trailing lambda can sit outside parentheses when it is the final parameter. it names a single implicit parameter. Closures capture variables and can observe later changes.',
 S('val f:(Int)->Int={it+1}; println(~f(${n})~)','${next}','${n}|Compile error','The function value is called like a named function.','f|${n}'),
 S('println(listOf("${word}").~map~ {it.length}.single())','${length}','0|Compile error','map transforms each element using its trailing lambda.','filter|onEach'),
 S('var n=${n}; val f={n}; n++; println(~f()~)','${next}','${n}|Compile error','The closure reads the current captured variable.','n-1|0'),
 S('fun apply(n:Int,f:(Int)->Int)=f(n)\nprintln(apply(${n}) ~{it+1}~)','${next}','${n}|Compile error','The trailing lambda supplies the final function parameter.','{it}|{0}')),
 L('scope','Scope functions and labeled returns','let and run return lambda results; also and apply return the receiver. let/also name it, while run/apply use this. These differences determine a chain result. A labeled return exits a specific lambda rather than an enclosing function.',
 S('val n="${word}".~let~ {it.length}; println(n)','${length}','${word}|Compile error','let returns the lambda result, here an Int.','also|apply'),
 S('val text="${word}".~also~ {it.length}; println(text)','${word}','${length}|Compile error','also returns the receiver regardless of the lambda result.','let|run'),
 S('val a=mutableListOf<Int>().~apply~ {add(${n})}; println(a.single())','${n}','true|Compile error','apply configures the receiver with this and returns the list.','run|let'),
 S('var n=0; listOf(0,1,2).forEach {if(it==1) ~return@forEach~;n++}; println(n)','2','1|Compile error','The labeled return skips only this callback invocation.','return|break')),
 L('sealed','Sealed hierarchies and exhaustive when','Sealed hierarchies describe a controlled set of alternatives. when can be exhaustive over them without a catch-all. Objects express singleton states; data subclasses carry payloads. Domain modeling should make impossible combinations harder to represent.',
 S('sealed interface State\ndata class Ready(val n:Int):State\ndata object Idle:State\nval x:State=Ready(${n}); println(when(x){is Ready -> x.n; ~Idle~ -> 0})','${n}','0|Compile error','The when handles both permitted alternatives.','else -> Idle|is String'),
 S('enum class Mode {READ,WRITE}\nprintln(Mode.~READ~.name)','READ','WRITE|Compile error','An enum constant has a stable declared name.','WRITE|valueOf("WRITE")'),
 S('data object Idle\nprintln(~Idle==Idle~)','true','false|Compile error','The singleton state compares equal to itself.','Idle!=Idle|false'),
 S('sealed interface Result\ndata class Ok(val text:String):Result\ndata object Missing:Result\nval x:Result=Ok("${word}"); if(x ~is Ok~) println(x.text)','${word}','No output|Compile error','A successful type check reveals the payload property.','is Missing|!is Ok')),
 L('generics','Variance and generic constraints','out marks a producer type parameter and in a consumer. Invariant mutable collections cannot freely substitute element types. Star projections support safe unknown-type reading. Generic bounds state required operations; JVM erasure limits runtime type tests.',
 S('fun <T> identity(x:~T~):T=x\nprintln(identity("${word}"))','${word}','Compile error|null','The generic parameter preserves the concrete argument type.','Any|String'),
 S('val names:List<String> = listOf("${word}"); val values:List<~Any~> = names; println(values.size)','1','0|Compile error','Read-only List is covariant, so a String producer is usable as an Any producer.','Int|Nothing'),
 S('val values:List<~*~> = listOf("${word}"); println(values.first())','${word}','Compile error|null','A star projection allows reading elements as a safe upper-bound type.','Int|Nothing'),
 S('fun <T:~CharSequence~> size(x:T)=x.length\nprintln(size("${word}"))','${length}','Compile error|0','The bound supplies the length property to the generic body.','Any|Number')),
 L('sequences','Lazy sequences and materialization','Collection transforms usually produce collections eagerly; Sequence transforms are lazy. Terminal operations drive evaluation. Converting a sequence to a list materializes a result. Choose laziness for a useful execution model, not as an automatic performance improvement.',
 S('var calls=0; val q=sequenceOf(${n}).map {calls++;it}; println(~calls~)','0','1|Compile error','No terminal operation has requested an element.','q.count()|calls+1'),
 S('println(sequenceOf(${n},0).~filter~ {it>0}.count())','1','2|0','The terminal count evaluates the filter.','map|onEach'),
 S('println(sequenceOf("${word}").~map~ {it.length}.first())','${length}','0|Compile error','map transforms the first requested value.','filter|onEach'),
 S('val a=mutableListOf(${n}); val snapshot=a.asSequence().~toList()~; a.add(${m}); println(snapshot.size)','1','2|Compile error','toList captures the elements before the later mutation.','asIterable()|map {it}')),
 L('errors','Exceptions, results, and preconditions','Kotlin has no checked-exception enforcement. try can be an expression. require validates caller arguments and check validates state. runCatching packages a result or Throwable; be careful not to accidentally swallow cancellation in coroutine code.',
 S('val n=try {"bad".toInt()} catch(e:NumberFormatException){~${n}~}; println(n)','${n}','Throws NumberFormatException|Compile error','The catch block produces the fallback value.','0|-1'),
 S('println("bad".~toIntOrNull~() ?: ${n})','${n}','Throws NumberFormatException|Compile error','The nullable parsing API reports malformed input as null.','toInt|toLong'),
 S('val result=~runCatching~ {error("${word}")}; println(result.isFailure)','true','false|Uncaught exception','runCatching represents the thrown failure in Result.','run|let'),
 S('try {~require~(false){"${word}"}} catch(e:IllegalArgumentException){println(e.message)}','${word}','No output|Uncaught IllegalStateException','require throws IllegalArgumentException for an invalid precondition.','check|assert')),
 L('interop','Java interoperability and resource use','Kotlin/JVM can call Java APIs. Platform types from Java may lack reliable nullability annotations; validate at the boundary. use closes supported resources after the block. internal visibility is module-level, while private limits implementation scope.',
 S('val r=java.io.StringReader("${word}"); r.~use~ {println(it.readText())}','${word}','No output|Compile error','use closes the reader on normal and exceptional exits.','also|let'),
 S('println(java.lang.Integer.~parseInt~("${n}")+1)','${next}','${n}|Compile error','The Java static parsing method is directly callable.','toString|valueOf("0").compareTo'),
 S('~internal~ fun size()=${n}','Visible within the Kotlin compilation module','Public to every Kotlin module|Private to one function','internal is a Kotlin module boundary, not a Java package boundary.','public|private','What visibility does this declaration request?'),
 S('object Settings {val limit=${n}}\nprintln(~Settings.limit~)','${n}','Compile error|0','An object declaration exposes one lazily initialized singleton instance.','Settings().limit|Settings.limit()')),
 L('suspension','Suspend functions and coroutine boundaries','suspend allows suspension; it does not imply a background thread or launch work. A suspend function is called from another suspend function or coroutine machinery. kotlin.coroutines provides low-level continuations. launch, delay, and structured coroutine scopes belong to kotlinx.coroutines, a separate library deferred to a specialized track.',
 S('~suspend~ fun read():Int = ${n}','Can be called from a suspending context','Always starts a new thread|Automatically performs nonblocking file I/O','suspend changes the calling contract; this body itself returns immediately.','inline|tailrec','What does the modifier mean?'),
 S('suspend fun first()=${n}\nsuspend fun next()=~first()~+1','Returns ${next} when next is called and completes normally','Starts two threads|Compile error','A suspend function may call another suspend function normally.','Thread.sleep(1)|Unit','What is the result of next?'),
 S('suspend fun load()=java.io.File("notes.txt").~readText()~','File reading still blocks the calling thread','The file becomes nonblocking automatically|A coroutine is launched','suspend does not transform ordinary blocking I/O APIs.','exists()|length()','What execution property should a reviewer notice?'),
 S('// Inside a suspend function:\nval n=kotlin.coroutines.~suspendCoroutine~<Int>{continuation -> continuation.resumeWith(Result.success(${n}))}','Resumes with ${n}','Necessarily switches threads|Never resumes','The continuation is resumed immediately with a successful Int; no scheduler is introduced.','coroutineContext|Continuation','What value is produced?')),
 ]
