"""Bash reading-first track; safe authored fixtures, no learner execution."""
from build import S, lesson as L


def lessons():
 return [
 L('commands','Commands, arguments, and builtins','Bash parses commands into a command name and arguments. Whitespace separates words unless quoted. Builtins execute in the shell, while external utilities run as processes. The # character starts a comment when it begins an unquoted word. Examples use disposable state and no privileged commands.',
 S('~printf~ "%s\n" "${word}"','${word}','%s|No output','printf formats its arguments using a separate format string.','true|false'),
 S('printf "%s\n" ~"${word} item"~','${word} item','${word}\nitem|No output','Quotes keep the space inside one argument.','${word} item|"item"'),
 S('printf "%s\n" "${word}" ~# ignored~','${word}','${word}\nignored|Syntax error','The comment is not passed as command arguments.','ignored|"# ignored"'),
 S('~:~ "${word}"','No output; successful status','${word}|Command not found',': is the no-op builtin; arguments are expanded but nothing is printed.','printf|false','What does this command do?')),
 L('variables','Assignment and parameter expansion','Assignments have no spaces around =. Expansion substitutes a variable value; quote it to preserve its argument boundaries. Shell variables are strings until an arithmetic context interprets them. An empty value differs from an unset name.',
 S('name=${word}\nprintf "%s\n" ~"$name"~','${word}','name|No output','The dollar expansion reads name and the quotes preserve it as one word.','name|\'$name\''),
 S('n=${n}\nprintf "%s\n" ~"$n"~','${n}','n|0','An ordinary variable stores the assigned digit text.','n|0'),
 S('name=\'${word} item\'\nprintf "%s\n" ~"$name"~','${word} item','${word}\nitem|No output','Quoted expansion retains the embedded space.','$name|name'),
 S('name=${word}\n~unset~ name\nprintf "%s\n" "$name"','(empty)','${word}|name','unset removes the variable; without nounset, quoted expansion becomes an empty string.','export|readonly')),
 L('quoting','Single quotes, double quotes, and escapes','Single quotes suppress expansion; double quotes allow parameter and command expansion while preventing ordinary word splitting and globbing. Backslash can protect a special character. Reading quotes accurately is essential before running generated commands.',
 S('name=${word}\nprintf "%s\n" ~\'$name\'~','$name','${word}|name','Single quotes preserve the literal dollar sign and name.','"$name"|name'),
 S('printf "%s\n" ~"a b"~','a b','a\nb|ab','A quoted space belongs to one argument.','a b|ab'),
 S('printf "%s\n" ~\\*~','*','All filenames|Syntax error','The backslash makes the asterisk literal instead of a glob.','"word"|word'),
 S('name=${word}\nprintf "%s\n" "~\\$~name"','$name','${word}|name','Escaping the dollar sign inside double quotes prevents expansion.','$|')),
 L('status','Exit statuses and conditional lists','Zero means success; nonzero means failure. $? contains the most recent command status and is easily overwritten. && runs the next command after success; || runs it after failure. An exit status is distinct from text printed to stdout.',
 S('false\nprintf "%s\n" ~"$?"~','1','0|false','false sets a failure status of one.','0|true'),
 S('true ~&&~ printf "%s\n" "${word}"','${word}','No output|Syntax error','The right command runs after success.','|||&'),
 S('false ~||~ printf "%s\n" "${word}"','${word}','No output|Syntax error','The fallback runs after a failing command.','&&|&'),
 S('false\nstatus=$?\ntrue\nprintf "%s\n" ~"$status"~','1','0|No output','Saving the status before another command preserves the failure result.','"$?"|0')),
 L('arithmetic','Arithmetic expansion and integer conditions','Arithmetic expansion uses $((...)); arithmetic commands ((...)) use an expression value as success or failure. Bash arithmetic is integral. A zero arithmetic value gives status one, which can interact surprisingly with set -e. Never treat untrusted input as arbitrary arithmetic code.',
 S('printf "%s\n" "$(( ${n} ~+~ ${m} ))"','${add}','${mul}|${div}','Arithmetic expansion evaluates the sum into text.','*|/'),
 S('printf "%s\n" "$(( ${n} ~/~ ${m} ))"','${div}','${mul}|${add}','Integer division truncates the positive quotient.','*|+'),
 S('n=${n}\n~((n+=1))~\nprintf "%s\n" "$n"','${next}','${n}|0','The arithmetic command updates the shell variable.','((n-=1))|((n=0))'),
 S('~((0))~\nprintf "%s\n" "$?"','1','0|Syntax error','A zero arithmetic result is false and gives nonzero status.','((1))|true')),
 L('conditions','Tests and branches','[[...]] is Bash conditional syntax; it avoids ordinary splitting and pathname expansion of variable operands. -n tests nonempty text, -z tests empty text, and -eq compares integers. [ is a command and requires carefully separated, quoted arguments.',
 S('if [[ ${n} ~-gt~ 0 ]]; then printf "yes\n"; else printf "no\n"; fi','yes','no|Syntax error','-gt performs an integer comparison.','-lt|-eq'),
 S('name=${word}\nif [[ ~-n~ "$name" ]]; then printf "yes\n"; fi','yes','No output|Syntax error','-n succeeds for a nonempty string.','-z|-d'),
 S('name=\'\'\nif [ ~-z~ "$name" ]; then printf "empty\n"; fi','empty','No output|Syntax error','The quoted empty value remains an argument to the test command.','-n|-d'),
 S('if ~false~; then printf "yes\n"; else printf "no\n"; fi','no','yes|Syntax error','if tests a command exit status, not the printed word false.','true|:')),
 L('positionals','Positional parameters and argument preservation','Scripts and functions receive positional parameters. $# counts them; "$@" expands each argument as a separate word. "$*" joins arguments into one word using the first IFS character. shift removes the first positional argument.',
 S('set -- "${word} item" other\nprintf "%s\n" ~"$#"~','2','3|1','There are two arguments, including one with a space.','"$1"|"$2"'),
 S('set -- "${word} item" other\nprintf "<%s>\n" ~"$@"~','<${word} item>\n<other>','<${word}>\n<item>\n<other>|<${word} item other>','Quoted at expansion preserves each original argument boundary.','$@|"$*"'),
 S('set -- "${word}" other\n~shift~\nprintf "%s\n" "$1"','other','${word}|No output','shift discards the first positional parameter.','true|:'),
 S('set -- "${word}"\nprintf "%s\n" ~"$1"~','${word}','1|No output','The first script argument is $1; $0 names the invoked script or shell.','1|"$#"')),
 L('expansion','Defaults and string operations','Bash parameter operators can provide defaults, assign missing values, or remove patterns. The colon forms treat both unset and empty as missing; forms without a colon distinguish them. # and % remove prefix and suffix patterns, not regular expressions.',
 S('unset name\nprintf "%s\n" ~"${name:-${word}}"~','${word}','Empty string|Syntax error','The colon-minus form provides a fallback without assigning name.','"$name"|"name"'),
 S('name=\'\'\nprintf "%s\n" ~"${name-${word}}"~','(empty)','${word}|Syntax error','Without the colon, a set-but-empty value does not trigger the fallback.','"${name:-${word}}"|"${word}"'),
 S('name=${word}.txt\nprintf "%s\n" ~"${name%.txt}"~','${word}','${word}.txt|txt','Percent removes a matching suffix pattern once.','"$name"|"${name#*.}"'),
 S('name=folder/${word}\nprintf "%s\n" ~"${name##*/}"~','${word}','folder/${word}|folder','Double hash removes the longest matching prefix ending with slash.','"$name"|"${name%/*}"')),
 L('globbing','Filename expansion and literal patterns','Globs match filenames after word splitting. Quoting suppresses glob expansion. By default an unmatched pattern remains literal; nullglob removes it and failglob errors. Hidden names need explicit treatment. Use disposable directories to inspect expansion safely.',
 S('printf "%s\n" ~"*.txt"~','*.txt','All text filenames|No output','Quoting keeps the pattern literal regardless of directory contents.','"txt"|"*"'),
 S('shopt -s nullglob\nset -- ~./no-match-for-codelingo-*.xyz~\nprintf "%s\n" "$#"','0','1|Syntax error','Assume a fresh empty directory. nullglob removes the unmatched pattern.','"./no-match-for-codelingo-*.xyz"|literal','In an empty directory, what prints?'),
 S('shopt -u nullglob failglob\nset -- ~./no-match-for-codelingo-*.xyz~\nprintf "%s\n" "$#"','1','0|Syntax error','Without nullglob or failglob, an unmatched pattern remains one literal argument.','"" ""|','In an empty directory, what prints?'),
 S('name=${word}.txt\nif [[ $name == ~*.txt~ ]]; then printf "match\n"; fi','match','No output|Syntax error','An unquoted right-hand pattern in [[ == ]] performs pattern matching.','"*.txt"|"txt"')),
 L('loops','Looping over arguments and lines','for iterates words, while loops test command statuses. Preserve "$@" to iterate original arguments. read -r avoids treating backslash as an escape and IFS= preserves leading/trailing whitespace. Reading lines is different from splitting a command substitution.',
 S('set -- "${word} item" other\nfor item in ~"$@"~; do printf "<%s>\n" "$item"; done','<${word} item>\n<other>','<${word}>\n<item>\n<other>|<${word} item other>','Quoted positional expansion keeps each argument intact through iteration.','$@|"$*"'),
 S('n=0\nfor ((i=0;i<${n};i++)); do ((n+=1)); done\nprintf "%s\n" ~"$n"~','${n}','0|${next}','The arithmetic for loop executes ${n} times.','0|"$i extra"'),
 S('n=0\nfor i in 0 1 2; do if [[ $i == 1 ]]; then ~continue~; fi; ((n+=1)); done\nprintf "%s\n" "$n"','2','1|3','continue skips only the selected iteration.','break|return'),
 S('IFS= ~read -r~ line <<< "${word} item"\nprintf "%s\n" "$line"','${word} item','${word}|No output','IFS= and -r preserve the line content; read removes the record newline.','read -n 1|read -n 2')),
 L('functions','Function scope and return status','Functions run in the current shell unless a subshell context changes that. local limits a variable to a function call and its dynamically nested calls. return sets a status, not a string result. Capture stdout when a function produces text.',
 S('name=outer\nf(){ ~local~ name=${word}; printf "%s\n" "$name"; }\nf\nprintf "%s\n" "$name"','${word}\nouter','${word}\n${word}|outer','local protects the outer variable from this assignment.','export|readonly'),
 S('f(){ ~return~ 7; }\nf\nprintf "%s\n" "$?"','7','0|No output','return supplies a numeric command status.','printf|echo'),
 S('f(){ printf "%s\n" "${word}"; }\nname=~$(f)~\nprintf "%s\n" "$name"','${word}','f|No output','Command substitution captures stdout, not the function exit status.','f|\'$(f)\''),
 S('f(){ printf "%s\n" "$1"; }\nf ~"${word} item"~','${word} item','${word}|item','The quoted call argument becomes one function positional parameter.','${word} item|item')),
 L('redirection','File descriptors and redirection order','Descriptor 0 is stdin, 1 stdout, and 2 stderr. > truncates and >> appends. Redirections are processed left to right: 2>&1 copies the current stdout destination rather than creating a permanent link. Use printf with a fixed format for arbitrary data.',
 S('printf "%s\n" "${word}" ~>~ result.txt','Replaces result.txt with one line','Appends to the file|Reads the file','Output redirection creates or truncates this file before writing.','>>|<','What happens in a writable temporary directory?'),
 S('printf "%s\n" "${word}" ~>>~ result.txt','Appends one line to result.txt','Always truncates the file|Reads the file','Append redirection retains existing content.','>|<','What happens in a writable temporary directory?'),
 S('printf "%s\n" "${word}" ~>&2~','Writes the line to stderr','Writes only to stdout|Sets status 2','This redirects stdout of printf to the shell stderr destination.','>&1|>/dev/null','Where is the line sent?'),
 S('{ printf "out\n"; printf "err\n" >&2; } ~>out.txt 2>&1~','Both stdout and stderr go to out.txt','Only stderr goes to out.txt|Stderr keeps the old stdout destination','First stdout becomes the file; then stderr duplicates that destination.','2>&1 >out.txt|2>out.txt','How are the streams routed?')),
 L('pipelines','Pipelines and pipefail','A pipeline connects stdout of one command to stdin of the next. Its default status is that of the last command. pipefail changes it to the rightmost failing command status, or zero. Pipeline components commonly run in subshells, so state updates may not survive.',
 S('set +o pipefail\nfalse ~|~ true\nprintf "%s\n" "$?"','0','1|Syntax error','Without pipefail, the successful final command determines status.','&&|; false;'),
 S('set -o ~pipefail~\nfalse | true\nprintf "%s\n" "$?"','1','0|Syntax error','pipefail preserves the failure of the earlier component here.','noclobber|noglob'),
 S('printf "%s\n" "${word}" ~|~ cat','${word}','No output|Syntax error','The pipe passes printf stdout to cat stdin.','&&|;'),
 S('set +m\nshopt -u lastpipe\nn=0\nprintf "x\n" | { read -r line; n=1; }\nprintf "%s\n" ~"$n"~','0','1|Syntax error','With lastpipe disabled, the final pipeline group runs in a subshell and cannot update the parent n.','1|"$line"')),
 L('subshells','Subshells and grouped commands','Parentheses execute commands in a subshell environment; braces group commands in the current shell. Command substitution also normally uses a subshell and removes trailing newlines. Neither an inner variable assignment nor cd automatically changes the parent shell.',
 S('n=${n}\n~(n=0)~\nprintf "%s\n" "$n"','${n}','0|Syntax error','The subshell assignment does not modify the parent variable.','{ n=0; }|n=0'),
 S('n=${n}\n~{ n=0; }~\nprintf "%s\n" "$n"','0','${n}|Syntax error','Brace grouping runs in the current shell environment.','(n=0)|true'),
 S('name=$(printf "${word}\n\n")\nprintf "<%s>\n" ~"$name"~','<${word}>','<${word}\n\n>|Empty output','Command substitution removes all trailing newlines from captured stdout.','name|\'$name\''),
 S('n=${n}\nname=$(n=0;printf "${word}")\nprintf "%s\n" ~"$n"~','${n}','0|Syntax error','Assignments inside command substitution stay inside its subshell.','0|"$name"')),
 L('arrays','Indexed and associative arrays','Bash arrays retain argument boundaries when expanded as "${array[@]}". Indexed arrays are sparse; their element count is not their largest index plus one. Associative arrays use string keys and require declare -A. Bash variables cannot contain NUL bytes.',
 S('items=("${word} item" other)\nprintf "<%s>\n" ~"${items[@]}"~','<${word} item>\n<other>','<${word}>\n<item>\n<other>|<${word} item other>','Quoted array-at expansion preserves each stored element.','${items[@]}|"${items[*]}"'),
 S('items=()\nitems[5]=${word}\nprintf "%s\n" ~"${#items[@]}"~','1','6|0','Only one index is assigned, so the element count is one.','"${items[5]}"|6'),
 S('~declare -A~ sizes\nsizes[${word}]=${n}\nprintf "%s\n" "${sizes[${word}]}"','${n}','0|Syntax error','declare -A creates an associative array with string keys.','declare -i|declare -f'),
 S('items=("${word}")\nitems+=(other)\nprintf "%s\n" ~"${#items[@]}"~','2','1|0','The += compound assignment appends an element.','"${items[0]}"|1')),
 L('patterns','Case patterns and regular expressions','case uses shell patterns, while [[ =__TILDE__ ]] uses an extended regular expression. Regex captures appear in BASH_REMATCH. Quoting the entire regex makes quoted portions literal. These are distinct pattern languages, so do not transfer operators blindly.',
 S('name=${word}.txt\ncase $name in ~*.txt~) printf "text\n";; *) printf "other\n";; esac','text','other|Syntax error','The shell pattern matches any prefix followed by .txt.','"*.txt"|*.csv'),
 S('name=${word}\nif [[ $name =__TILDE__ ~^[a-z]+$~ ]]; then printf "letters\n"; fi','letters','No output|Syntax error','The regex requires one or more lowercase ASCII letters.','^[0-9]+$|^$'),
 S('text=id:${n}\nif [[ $text =__TILDE__ ^id:([0-9]+)$ ]]; then printf "%s\n" ~"${BASH_REMATCH[1]}"~; fi','${n}','id:${n}|No output','Capture group one contains only the digits.','"${BASH_REMATCH[0]}"|0'),
 S('name=${word}\ncase $name in ~${word}~) printf "yes\n";; *) printf "no\n";; esac','yes','no|Syntax error','This literal case pattern matches the generated name exactly.','other|missing')),
 L('environment','Environment inheritance and script loading','export makes a variable available to child processes. A child cannot directly rebind its parent variables. A prefix assignment configures one command environment. source executes a file in the current shell; bash file runs a new shell. Script input should be treated as data, not eval code.',
 S('~export~ DEMO=${word}\nbash -c \'printf "%s\n" "$DEMO"\'','${word}','Empty string|Syntax error','The child shell inherits an exported variable.','readonly|local'),
 S('DEMO=outer\nDEMO=${word} bash -c \'printf "%s\n" "$DEMO"\'\nprintf "%s\n" ~"$DEMO"~','${word}\nouter','${word}\n${word}|outer','The prefix assignment affects the child command but not the parent variable after it returns.','"${word}"|"other"'),
 S('# Assume helpers.sh contains function definitions only.\n~source~ helpers.sh','Loads definitions into the current shell','Runs in an isolated child only|Compiles helpers.sh','source executes the file in the current environment, so its definitions persist.','bash|cat','Where are the definitions loaded?'),
 S('export DEMO=${word}\nbash -c \'DEMO=other\'\nprintf "%s\n" ~"$DEMO"~','${word}','other|No output','The child assignment does not change the parent environment.','other|0')),
 L('traps','Traps, cleanup, and failure boundaries','trap registers actions for signals or shell exit. Quote the action so expansion occurs at the intended time. EXIT is useful for temporary-file cleanup; exec replaces the shell and changes lifecycle assumptions. set -e has context-dependent exceptions and is not a substitute for explicit status handling.',
 S('~trap~ \'printf "cleanup\n"\' EXIT\nprintf "%s\n" "${word}"','${word}\ncleanup','cleanup\n${word}|${word}','The EXIT action runs when this shell finishes.','true|:'),
 S('name=before\ntrap \'printf "%s\n" "$name"\' EXIT\nname=~${word}~','${word}','before|No output','Single quotes defer variable expansion until the trap executes.','before|other'),
 S('trap \'printf "cleanup\n"\' EXIT\ntrap ~-~ EXIT\nprintf "%s\n" "${word}"','${word}','${word}\ncleanup|Syntax error','A dash resets the trap to its default disposition.','\'printf "cleanup\n"\'|\'printf "other\n"\''),
 S('set -e\nif ~false~; then printf "yes\n"; fi\nprintf "alive\n"','alive','No output|Shell always exits','A failing command tested by if is an errexit exception.','true|:')),
 L('processes','Background jobs and waiting','& starts an asynchronous job, and $! identifies the most recent background process. wait obtains completion and its status. A successful launch does not imply successful work. exec replaces the current process image, so commands after a successful exec do not run.',
 S('(exit 7) &\npid=$!\n~wait~ "$pid"\nprintf "%s\n" "$?"','7','0|No output','wait returns the background job exit status.','true|:'),
 S('printf "%s\n" "${word}" &\n~wait~','${word}','No output|Syntax error','wait keeps this shell alive until its background work completes.','false|:'),
 S('~exec~ bash -c \'printf "${word}\n"\'\nprintf "after\n"','${word}','${word}\nafter|after','A successful exec replaces the shell, so the following line is never executed.','command|'),
 S('(exit 0) &\npid=~$!~\nwait "$pid"\nprintf "%s\n" "$?"','0','1|Syntax error','$! identifies the child that wait must observe.','$?|0')),
 L('robustness','Safe argument construction and script checks','Use arrays to construct commands without reparsing strings through eval. bash -n checks syntax without executing the script, but does not prove correctness. printf with a constant format keeps data from becoming a format string. Explicitly validate argument counts and return failures at the boundary.',
 S('args=(printf "%s\n" "${word} item")\n~"${args[@]}"~','${word} item','${word}\nitem|Command not found','Quoted array expansion invokes the command with the stored argument boundaries.','${args[@]}|"${args[*]}"'),
 S('$ bash ~-n~ script.sh','Checks syntax without executing script commands','Proves the script safe|Runs the script with tracing','Syntax checking catches parse errors but not all runtime or logic failures.','-x|-v','What check is requested?'),
 S('text=\'%s\'\nprintf ~"%s\n"~ "$text"','%s','Empty string|Syntax error','A fixed format makes the percent sequence ordinary argument data.','"$text"|"literal\n"'),
 S('set -- "${word}"\nif [[ $# ~-ne~ 1 ]]; then exit 2; fi\nprintf "%s\n" "$1"','${word}','No output; status 2|Syntax error','The argument-count check succeeds for exactly one supplied argument.','-eq|-gt')),
 ]
