from build import S,lesson as L,emit,source

def typescript():
 return [
 L('values','Bindings and primitive types','Use let for reassignment and const for a binding that cannot be reassigned. Type annotations constrain assignments; they do not convert values at runtime. Assume strict mode throughout.',
 S('let x: number=~${n}~; console.log(x);','${n}','0|undefined','The numeric initializer is stored in x.','"${n}"|true'),
 S('let x=${n}; x=~${m}~; console.log(x);','${m}','${n}|undefined','let permits reassignment to another value of the inferred number type.','"${m}"|true'),
 S('~const~ x=${n}; x=${m};','Type error: cannot reassign const','Prints ${m}|Changes the binding','const prevents reassignment of this binding.','let|var','What does the checker report?'),
 S('let x:~number~=${n}; console.log(typeof x);','number','string|object','The annotation agrees with the numeric runtime value.','string|boolean')),
 L('expressions','Numbers and string expressions','JavaScript number division keeps fractions. + concatenates when an operand is a string. === compares without numeric coercion. TypeScript follows JavaScript runtime arithmetic.',
 S('console.log(~${n}+${m}~);','${add}','${mul}|${n}${m}','Two numeric operands are added.','${n}*${m}|"${n}"+${m}'),
 S('console.log(~"${n}"+${m}~);','${n}${m}','${add}|NaN','A string operand makes + concatenate text.','${n}+${m}|${n}*${m}'),
 S('console.log(~Math.floor(${n}/${m})~);','${div}','${rem}|${mul}','Math.floor rounds the positive quotient down.','${n}%${m}|${n}*${m}'),
 S('console.log("${word}".~toUpperCase()~);','${upper}','${word}|undefined','toUpperCase returns uppercase text.','toLowerCase()|length')),
 L('branches','Branches and narrowing','Control-flow analysis narrows union types after checks such as typeof. Nullish coalescing falls back for null or undefined, while || also falls back for other falsey values.',
 S('function f(x:string|number){if(typeof x~===~"string") return x.length; return x;} console.log(f("${word}"));','${length}','${word}|Type error','The typeof check narrows x to string in the branch.','!==|<'),
 S('let x:number|null=null; console.log(x ~??~ ${n});','${n}','null|0','Nullish coalescing supplies a fallback for null.','&&|==='),
 S('const x=0; console.log(x ~??~ ${n});','0','${n}|undefined','Nullish coalescing preserves zero.','|||+'),
 S('console.log(~false~ ? ${n} : ${m});','${m}','${n}|undefined','The false branch supplies the value after the colon.','true|${n}')),
 L('loops','Loops and iteration','for...of iterates values; for...in enumerates keys. A strict upper bound excludes the endpoint. continue skips the rest of the current iteration.',
 S('let x=0; for(let i=0;i~<~${n};i++) x++; console.log(x);','${n}','${next}|0','The exclusive upper bound gives ${n} iterations.','<=|>'),
 S('let x=0; for(const v ~of~ [${n},${m}]) x+=v; console.log(x);','${add}','${mul}|0','for...of supplies each numeric value.','in|as'),
 S('let x=0; for(let i=0;i<3;i++){if(i===1) ~continue~; x++;} console.log(x);','2','1|3','continue skips the middle increment.','break|return'),
 S('for(const k ~in~ {name:"${word}"}) console.log(k);','name','${word}|undefined','for...in enumerates the property key.','of|as')),
 L('functions','Functions and parameter contracts','Parameter and return annotations describe a function contract. Defaults handle omitted or undefined arguments. Rest parameters gather trailing arguments into an array.',
 S('function bump(x:number):number{return ~x+1~;} console.log(bump(${n}));','${next}','${n}|undefined','The return expression adds one.','x|0'),
 S('function size(x=${n}){return x;} console.log(~size()~);','${n}','undefined|0','The omitted argument uses the default.','size(0)|size(${m})'),
 S('function count(~...xs~:number[]){return xs.length;} console.log(count(${n},${m}));','2','1|Type error','The rest parameter gathers both arguments.','xs|..xs'),
 S('const f=(x:number)~=>~x*2; console.log(f(${n}));','${double}','${n}|undefined','The arrow expression implicitly returns its result.','=|->')),
 L('objects','Object types and interfaces','Object types describe required properties structurally. Optional properties may be absent. readonly restricts writes through a type but does not freeze the runtime object.',
 S('interface Box {size:number} const b:Box={size:${n}}; console.log(b.~size~);','${n}','undefined|Type error','The interface requires a numeric size property.','value|length'),
 S('interface Box {name~?~:string} const b:Box={}; console.log(b.name);','undefined','null|Type error','The optional property may be absent.','!|='),
 S('interface Box {~readonly~ size:number} const b:Box={size:${n}}; b.size=${m};','Type error: readonly property','Updates with no type error|Freezes every object','readonly prevents this assignment through the declared type.','public|mutable','What does the type checker report?'),
 S('type Box={size:number}; const item={size:${n},name:"${word}"}; const b:Box=~item~; console.log(b.size);','${n}','Type error|undefined','Structural compatibility permits this existing object with the required property.','{}|{name:"${word}"}')),
 L('arrays','Arrays, tuples, and destructuring','Arrays contain a chosen element type; tuples describe fixed positions. Destructuring extracts values; spread constructs shallow copies. No data-structure implementation is taught here.',
 S('const a:number[]=[${n},${m}]; console.log(a[~0~]);','${n}','${m}|undefined','Index zero selects the first element.','1|2'),
 S('const t:[number,string]=[${n},"${word}"]; console.log(t[~1~]);','${word}','${n}|Type error','The tuple second position is a string.','0|2'),
 S('const a=[${n}]; const b=~[...a]~; b[0]=${m}; console.log(a[0]);','${n}','${m}|undefined','Spread creates a separate outer array.','a|[]'),
 S('const {name:~label~}={name:"${word}"}; console.log(label);','${word}','undefined|Type error','The destructuring alias binds the property value to label.','name|text')),
 L('modules','Modules and type-only imports','export exposes module members. import brings them into another module. import type is erased and cannot supply a runtime value. File boundaries are stated in each snippet.',
 S('// config.ts\n~export~ const size=${n};\n// app.ts\nimport {size} from "./config"; console.log(size);','${n}','Type error|undefined','A named export can be imported with braces.','default|declare'),
 S('// config.ts\nexport default ${n};\n// app.ts\nimport ~size~ from "./config"; console.log(size);','${n}','Type error|undefined','A default import chooses a local name without braces.','{size}|* size'),
 S('// types.ts exports interface Box {size:number}\nimport ~type~ {Box} from "./types";','Removed from emitted JavaScript','Loads a runtime Box constructor|Freezes all Box objects','A type-only import is erased during compilation.','value|class','What happens to this import at runtime?'),
 S('// config.ts exports const size=${n}\nimport {size ~as~ amount} from "./config"; console.log(amount);','${n}','undefined|Type error','as renames an imported binding locally.','to|=')),
 L('errors','Unknown errors and safe handling','With strict checking, catch variables are unknown. Narrow them before reading properties. Throwing and catching follow JavaScript runtime rules; annotations do not validate external data.',
 S('try {throw new Error("${word}");} catch(e){if(e ~instanceof~ Error) console.log(e.message);}','${word}','undefined|Type error','instanceof narrows e to Error before accessing message.','typeof|==='),
 S('try {console.log(${n});} ~finally~ {console.log(${m});}','${n}\n${m}','${n}|${m}','finally executes after the try block.','else|catch'),
 S('let x:unknown="${word}"; if(~typeof x==="string"~) console.log(x.length);','${length}','undefined|Type error','typeof narrows unknown to string before the property access.','x!==null|true'),
 S('const x="${word}" as ~unknown as number~; console.log(typeof x);','string','number|Throws','Type assertions do not convert the runtime string into a number.','string|never','What is the runtime type after this assertion?')),
 L('classes','Classes and access control','Classes define instance state and methods. TypeScript private is checked statically; JavaScript # fields enforce runtime privacy. extends inherits implementation.',
 S('class Box {constructor(public size:number){}} console.log(new Box(${n}).~size~);','${n}','undefined|Type error','A public parameter property initializes an instance field.','value|length'),
 S('class Box {private size=${n}; get(){return ~this.size~;}} console.log(new Box().get());','${n}','undefined|Type error','A class method can access its own private property.','size|Box.size'),
 S('class Base {get(){return ${n};}} class Child ~extends~ Base {} console.log(new Child().get());','${n}','undefined|Type error','extends inherits the base method.','implements|as'),
 S('class Box {#size=${n}; get(){return this.~#size~;}} console.log(new Box().get());','${n}','undefined|Type error','A # field is accessed with its private identifier inside the class.','size|value')),
 L('generics','Generics and constraints','Generics connect types across a function without discarding information. Constraints require available operations. keyof forms a union of property names.',
 S('function id<T>(x:T):T{return ~x~;} console.log(id(${n}));','${n}','undefined|Type error','The generic preserves the argument type and value.','0|undefined'),
 S('function size<T ~extends~ {length:number}>(x:T){return x.length;} console.log(size("${word}"));','${length}','Type error|undefined','The constraint guarantees a numeric length property.','implements|as'),
 S('type Box={size:number}; type Key=~keyof~ Box;','"size"','number|Box','keyof produces the property-name union for the object type.','typeof|readonly','What type does Key represent?'),
 S('function get<T,K extends keyof T>(x:T,k:K):T[K]{return ~x[k]~;} console.log(get({size:${n}},"size"));','${n}','undefined|Type error','The constrained key safely indexes the corresponding property type.','x|k')),
 L('unions','Discriminated unions and exhaustiveness','A common literal tag distinguishes union members. Checking the tag narrows available fields. never represents an impossible remaining case in an exhaustive switch.',
 S('type Item={kind:"text",value:string}|{kind:"count",value:number}; function read(x:Item){return x.kind===~"text"~ ? x.value.length : x.value;} console.log(read({kind:"text",value:"${word}"}));','${length}','${word}|Type error','The literal tag narrows value to string in the first branch.','"count"|"other"'),
 S('type Mode="read"|"write"; const mode:Mode=~"read"~; console.log(mode);','read','undefined|Type error','Only declared string literals are assignable to this union.','"run"|"other"'),
 S('function impossible(x:~never~):never{throw new Error(String(x));}','Accepts no ordinary reachable value','Accepts every value|Converts values to strings','never can verify that an exhaustively handled union has no remaining case.','unknown|any','What does this parameter type express?'),
 S('const x={kind:"text",value:"${word}"} ~as const~;','Properties inferred readonly with literal types','Object is frozen at runtime|Values become any','as const preserves literal types and readonly properties in the type system.','as any|as unknown','What inference is requested?')),
 L('utilities','Mapped types and type operators','Utility types transform existing contracts. Partial makes properties optional; Pick selects properties; Readonly restricts assignment. satisfies checks compatibility while retaining useful inference.',
 S('type Box={size:number,name:string}; const b:~Partial<Box>~={size:${n}}; console.log(b.size);','${n}','Type error|undefined','Partial makes every property optional, allowing name to be omitted.','Box|Required<Box>'),
 S('type Box={size:number,name:string}; type Size=~Pick<Box,"size">~;','An object type with only size:number','Only the string literal size|A number primitive','Pick selects the named properties and their existing types.','Omit<Box,"size">|keyof Box','What type is Size?'),
 S('type Box={size:number}; const b:~Readonly<Box>~={size:${n}}; b.size=${m};','Type error: readonly property','Updates with no type error|Freezes the object at runtime','Readonly transforms the property contract to prohibit assignment through b.','Box|Partial<Box>','What does the checker report?'),
 S('const b={size:${n}} ~satisfies~ {size:number}; console.log(b.size+1);','${next}','${n}|Type error','satisfies checks the shape without replacing the inferred object type.','extends|implements')),
 L('async','Promises, async, and type erasure','async returns a Promise. await unwraps fulfillment inside an async function. Rejections use exception handling. Types are erased; runtime input still requires validation.',
 S('async function value(){return ${n};} value().~then~(x=>console.log(x));','${n}','Promise object|undefined','then runs with the fulfilled number.','catch|finally'),
 S('async function run(){const x=~await~ Promise.resolve(${n}); console.log(x+1);} run();','${next}','${n}|Type error','await obtains the fulfilled value before addition.','void|typeof'),
 S('Promise.reject(new Error("${word}")).~catch~((e:Error)=>console.log(e.message));','${word}','undefined|Uncaught rejection','catch handles the rejected promise.','then|finally'),
 S('type Box={size:number}; const raw:unknown=JSON.parse("{\"size\":\"${word}\"}"); const b=raw ~as Box~; console.log(typeof b.size);','string','number|Type assertion throws','An assertion performs no runtime validation or conversion.','as any|as never','What is printed at runtime?'))]

def web():
 return [
 L('html','HTML structure and semantics','HTML marks up content and meaning. Tags form elements; attributes configure them. A document has metadata in head and visible content in body. These are vanilla browser examples.',
 S('<~h1~>${word}</h1>','A top-level heading','A paragraph|A link','h1 identifies the page primary heading.','p|span','What semantic element is this?'),
 S('<a ~href~="/guide">${word}</a>','A link to /guide','An image|A text input','href specifies the link destination.','src|alt','What does this element provide?'),
 S('<img src="icon.png" ~alt~="${word}">','A text alternative of ${word}','A tooltip only|An image width','alt supplies a textual alternative for the image.','title|width','What accessibility information is provided?'),
 S('<~title~>${word}</title>','The document title','A visible main heading|A CSS selector','title belongs in head and names the document for browser UI.','h1|p','What does this head element define?')),
 L('forms','Forms and accessible controls','Labels connect to controls by id. name supplies the submitted field name. button type matters inside forms; required enables browser constraint validation.',
 S('<label ~for~="name">Name</label><input id="name" name="user">','The label targets input id name','Submits a field called for|Creates a placeholder','for matches the control id to associate its label.','name|href','What is the label association?'),
 S('<input ~name~="user" value="${word}">','user=${word}','value=${word}|name=user','name identifies the key submitted with this successful control.','id|class','What name-value pair is submitted?'),
 S('<form><button type="~button~">Open help</button></form>','No default form submission','Submits the form|Resets the form','An explicit button type avoids the default submit behavior.','submit|reset','What is the default action of this button?'),
 S('<input type="text" ~required~>','Empty input fails constraint validation','Empty input is always accepted|Input is read-only','required makes an empty text field invalid for normal validated submission.','readonly|disabled','Which validation behavior applies?')),
 L('css','Selectors and the cascade','CSS selectors choose elements. For competing declarations of the same origin, importance, and layer, specificity precedes source order. Class selectors use a dot and ID selectors use #.',
 S('<p class="note">${word}</p>\n<style>~.note~ {color: red;}</style>','The paragraph text is red','The page background is red|The rule matches nothing','A dot selector matches the class attribute.','#note|note','What does this rule do?'),
 S('<p id="item" class="note">${word}</p>\n<style>.note{color:blue} ~#item~{color:red}</style>','red','blue|Default color','The ID selector outranks the class selector in this cascade.','item|.item','What text color wins?'),
 S('<p>${word}</p>\n<style>p{color:blue} p{color:~red~}</style>','red','blue|Default color','Equal-specificity rules use the later declaration.','green|black','What color wins?'),
 S('<div class="card"><p>${word}</p></div>\n<style>~.card p~{color:red}</style>','Matches p descendants of .card','Matches only .card itself|Matches preceding paragraphs','The space is a descendant combinator.','.card+p|p .card','What does this selector match?')),
 L('layout','Box model and flex layout','content-box widths exclude padding and borders; border-box widths include them. Flexbox lays out children along a main axis. gap adds spacing between items.',
 S('.box {width: ${n}px; padding: 2px; border: 1px solid; box-sizing: ~content-box~;}','${boxwidth}px','${n}px|${plus2}px','Content width plus two paddings and two borders gives the outer width.','border-box|inherit','What is the outer width, ignoring margin?'),
 S('.box {width: ${nwide}px; padding: 2px; border: 1px solid; box-sizing: ~border-box~;}','${nwide}px','${wideplus6}px|${n}px','border-box includes padding and border inside the declared width.','content-box|initial','What is the outer width, ignoring margin?'),
 S('.row {display: ~flex~; flex-direction: row;}','Children use a horizontal main axis','Children become absolutely positioned|Children disappear','A row flex container lays out items along its horizontal main axis in normal horizontal writing mode.','block|none','What layout is established?'),
 S('.row {display:flex; ~gap~: ${n}px;}','${n}px between adjacent flex items','${n}px around every outer edge|${n}px text size','gap inserts spacing between items, not an outer margin.','padding|font-size','What spacing is requested?')),
 L('javascript','JavaScript values and branches','JavaScript adds behavior. let permits reassignment; const fixes a binding. + adds numbers or concatenates strings. === compares without coercion.',
 S('let x=${n}; x=~${m}~; console.log(x);','${m}','${n}|undefined','The later assignment replaces x.','${n}|0'),
 S('console.log(~${n}+${m}~);','${add}','${mul}|${n}${m}','Two numbers are added.','${n}*${m}|"${n}"+${m}'),
 S('console.log(${n} ~===~ "${n}");','false','true|Throws','Strict equality distinguishes number from string.','==|!='),
 S('console.log(~null~ ?? "${word}");','${word}','null|undefined','Nullish coalescing uses the fallback for null.','0|false')),
 L('functions','Functions, scope, and loops','Functions package behavior and return values. let has block scope. for...of visits values. Arrow functions can return a single expression implicitly.',
 S('function bump(x){return ~x+1~;} console.log(bump(${n}));','${next}','${n}|undefined','return supplies the computed value to the caller.','x|0'),
 S('const twice=x~=>~x*2; console.log(twice(${n}));','${double}','${n}|undefined','The arrow expression returns the doubled argument.','=|->'),
 S('let x=${n}; {~let~ x=${m};} console.log(x);','${n}','${m}|Syntax error','The inner block-scoped binding shadows the outer one.','var|function'),
 S('let x=0; for(const v ~of~ [${n},${m}]) x+=v; console.log(x);','${add}','${mul}|0','for...of yields both array values.','in|as')),
 L('dom','DOM selection and safe text updates','The DOM exposes elements as objects. querySelector returns the first match or null. textContent inserts text without parsing markup; classList manipulates class tokens.',
 S('<p id="msg">old</p>\n<script>document.~querySelector~("#msg").textContent="${word}";</script>','${word}','old|#msg','querySelector finds the paragraph and textContent replaces its text.','getElementById|getElementsByClassName','What text is visible?'),
 S('<p id="msg"></p>\n<script>document.querySelector("#msg").~textContent~="<b>${word}</b>";</script>','Literal text <b>${word}</b>','Bold ${word}|Nothing','textContent treats the angle brackets as text rather than HTML.','innerHTML|outerHTML','What does the paragraph show?'),
 S('const el=document.querySelector("#missing"); console.log(el ~===~ null);','true','false|Throws','A selector with no match returns null.','!==|>','Assume #missing does not exist. What is logged?'),
 S('const el=document.createElement("p"); el.classList.~add~("${word}"); console.log(el.className);','${word}','Empty string|undefined','classList.add adds one class token.','remove|contains')),
 L('events','Events and default actions','addEventListener registers a callback. target identifies the originating element; currentTarget identifies the current listener element. preventDefault and stopPropagation have different roles.',
 S('button.~addEventListener~("click",()=>console.log("${word}"));','${word}','Nothing|undefined','The listener callback runs on a click.','removeEventListener|dispatchEvent','After registering on an existing button, what does one click log?'),
 S('form.addEventListener("submit",event=>event.~preventDefault~());','Cancels the default form submission','Stops all bubbling only|Removes the form','preventDefault cancels the event default action when cancelable.','stopPropagation|stopImmediatePropagation','What does this call request?'),
 S('parent.addEventListener("click",event=>console.log(event.~target~.id));','child','parent|undefined','target remains the element that originated the bubbling event.','currentTarget|type','A child with id child is clicked inside parent. What is logged?'),
 S('child.addEventListener("click",event=>event.~stopPropagation~());','Prevents further ancestor propagation','Cancels every default action|Removes all listeners','stopPropagation prevents the event from continuing along the propagation path.','preventDefault|composedPath','What does this call do?')),
 L('data','Objects, arrays, and JSON','Objects hold named properties. Array operations work on values. Spread makes shallow copies; JSON is a text format and parsing it does not validate its shape.',
 S('const x={name:"${word}"}; console.log(x.~name~);','${word}','undefined|name','Dot access reads the named property.','value|length'),
 S('const a=[${n},${m}]; console.log(a.~map~(x=>x*2).join(","));','${double},${m_double}','${n},${m}|undefined','map creates an array of transformed values.','filter|forEach'),
 S('const x=JSON.~parse~(\'{"size":${n}}\'); console.log(x.size);','${n}','undefined|String text','JSON.parse converts valid JSON text into a JavaScript value.','stringify|rawJSON'),
 S('const a={size:${n}}; const b=~{...a}~; b.size=${m}; console.log(a.size);','${n}','${m}|undefined','Spread copies the numeric property into a new outer object.','a|null')),
 L('responsive','Responsive CSS and states','Media queries conditionally apply rules. Relative units adapt to context. :focus-visible supports keyboard focus styling. Prefer native interactive elements for built-in keyboard behavior.',
 S('@media (~max-width~: 600px) {.card{display:none}}','Hidden at a 500px viewport','Hidden only above 600px|Always visible','max-width applies when the viewport is no wider than 600 CSS pixels.','min-width|min-height','At viewport width 500px and height 800px, what happens?'),
 S('html{font-size:10px} .card{padding:~2rem~}','20px','2px|10px','rem uses the root font size.','2px|1rem','What is the computed padding?'),
 S('button:~focus-visible~ {outline:2px solid blue}','Styles visible keyboard-focus indication','Styles every visited link|Styles only disabled controls','focus-visible matches focus when the browser determines an indicator should be shown.','visited|disabled','What state does this selector address?'),
 S('<~button~ type="button">${word}</button>','Native keyboard-activatable button','Noninteractive generic container|Link to another page','button provides native button semantics and keyboard activation.','div|span','What semantics does this element provide?')),
 L('async','Promises and async execution','Promise callbacks run after current synchronous code. async functions return promises; await suspends the async function until settlement. Rejections can be caught.',
 S('console.log("a"); Promise.resolve().~then~(()=>console.log("b")); console.log("c");','a\nc\nb','a\nb\nc|b\na\nc','The promise callback runs after the current synchronous code finishes.','catch|finally'),
 S('async function run(){const x=~await~ Promise.resolve(${n}); console.log(x+1);} run();','${next}','${n}|[object Promise]','await obtains the fulfilled number before addition.','void|typeof'),
 S('Promise.reject(new Error("${word}")).~catch~(e=>console.log(e.message));','${word}','Uncaught rejection|undefined','catch handles the rejection and reads its message.','then|finally'),
 S('async function value(){return ${n};} console.log(value() ~instanceof~ Promise);','true','false|${n}','An async function always returns a Promise.','===|!==')),
 L('fetch','Fetch and response handling','fetch resolves to a Response for HTTP errors too; network failures reject. Check ok before parsing. response.json is asynchronous. These examples assume the stated server response.',
 S('const response=await fetch("/items"); console.log(response.~ok~);','false','true|Fetch automatically throws','ok is false for HTTP 404 even though fetch resolves normally.','redirected|bodyUsed','Assume status 404, no redirect, unread body. What is logged?'),
 S('const response=await fetch("/item"); const data=await response.~json()~; console.log(data.size);','${n}','undefined|[object Promise]','json parses the response body asynchronously.','text()|blob()','Assume a JSON body {"size":${n}}. What is logged?'),
 S('const response=await fetch("/item",{~method~:"POST"});','Sends an HTTP POST request','Sends GET with a query parameter|Changes only the response','method configures the HTTP request method.','mode|cache','What does this option do?'),
 S('const controller=new AbortController(); fetch("/item",{signal:controller.signal}).catch(()=>{}); controller.~abort~();','Requests cancellation of the fetch','Caches the response|Submits another request','abort signals cancellation to the associated request.','dispatchEvent|toString','What does the final call request?')),
 L('modules','Modules and closure state','Browser modules use type="module" and explicit exports. Module bindings have their own scope. Closures retain lexical variables; a const binding can still refer to a mutable object.',
 S('<script type="~module~" src="app.js"></script>','Loads app.js as an ES module','Loads a classic global script|Treats the file as JSON','type module enables module scope and import/export syntax.','text/javascript|application/json','How is the script interpreted?'),
 S('// config.js\n~export~ const size=${n};\n// app.js\nimport {size} from "./config.js"; console.log(size);','${n}','undefined|Syntax error','The named export makes size available to the importing module.','default|return'),
 S('function make(){let x=${n}; return ()=>~++x~;} const next=make(); console.log(next());','${next}','${n}|undefined','The closure retains and increments its private counter.','x|x--'),
 S('const x={size:${n}}; x.size=~${m}~; console.log(x.size);','${m}','${n}|TypeError','const fixes the object binding but permits property mutation.','${n}|0')),
 L('integration','DOM lifecycle and browser boundaries','defer runs a classic external script after parsing and before DOMContentLoaded. localStorage stores strings. Delegated handlers can use closest. Browser code is constrained by origin policies.',
 S('<script ~defer~ src="app.js"></script>','Runs after parsing, before DOMContentLoaded','Always runs before parsing completes|Runs only on click','defer delays execution of a classic external script until document parsing completes.','async|nomodule','When does the classic script execute?'),
 S('localStorage.setItem("size",String(${n})); console.log(typeof localStorage.~getItem~("size"));','string','number|object','localStorage retrieves stored values as strings.','key|removeItem'),
 S('list.addEventListener("click",e=>{const button=e.target.~closest~("button"); if(button) console.log(button.id);});','save','icon|list','closest finds the nearest matching ancestor or the element itself.','querySelector|matches','Click a span id icon inside a button id save inside list. What is logged?'),
 S('const response=await fetch("https://other.example/data",{mode:"~cors~"});','Requires the other origin to permit access with CORS','Bypasses all origin checks|Makes every response readable','cors requests cross-origin access subject to the server CORS response headers.','no-cors|same-origin','What access rule applies?'))]

def build():
 from build import DERIVED
 DERIVED.update(m_double='m*2',boxwidth='n+6',nwide='n+10',wideplus6='n+16')
 emit('typescript','TypeScript','TypeScript with strict checking; ES2022 JavaScript target; runtime output assumes successful type-checking unless the question explicitly asks otherwise', [source('ts','TypeScript Handbook','https://www.typescriptlang.org/docs/handbook/intro.html')],typescript())
 emit('web','Vanilla HTML + CSS + JavaScript','Modern standards-mode browser; scripts execute after their referenced elements exist unless timing is the topic; await snippets are inside async functions', [source('mdn','MDN core learning modules','https://developer.mozilla.org/en-US/docs/Learn_web_development/Core'),source('js','MDN JavaScript Guide','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide')],web())
